### ISSUE TITLE
Cmake issue

### ISSUE THREAD

**Issue by sidjoshi1993** [awslabs/amazon-kinesis-video-streams-producer-c#102]
It's throwing error when i am compile in mac.

Can't open perl script "/Configure": No such file or directory
This system (darwin64-x86_64-cc) is not supported. See file INSTALL for details.
make[2]: *** [build/src/project_libopenssl-stamp/project_libopenssl-configure] Error 1
make[1]: *** [CMakeFiles/project_libopenssl.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:93 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:64 (build_dependency)

**Comment by disa6302** [comment]
@sidjoshi1993 , 

Can you run `export MACOSX_DEPLOYMENT_TARGET=<your-mac-version>` and see if it works?

**Comment by sidjoshi1993** [comment]
Do you have any example to use this library for iOS?

**Comment by lherman-cs** [comment]
@sidjoshi1993 unfortunately, we don't have an example for iOS at this moment.

**Comment by sidjoshi1993** [comment]
@lherman-cs  Ok, Thanks

**Comment by sidjoshi1993** [comment]
@lherman-cs 
I got error com/amazonaws/kinesis/video/client/Include.h not found.
I have found only a "common" and "cproducer" folder not found any "client" folder.
Can you help me fix it?

**Comment by lherman-cs** [comment]
@sidjoshi1993 make sure that `INCLUDE_PATH` is set to the right folder, this is to find your include files. 

Normally, you don't have to set `INCLUDE_PATH` manually since our cmake will configure this automatically. Could you share the latest logs from cmake to give us more context? Also, how did you configure the project? Did you build the dependencies manually?

**Comment by dhruv-dhola** [comment]
Step:1 I download the code from this from this git url 
	git clone https://github.com/awslabs/amazon-kinesis-video-streams-pic.git

Step2: And create build directory and execute Cmake from it like this 
    mkdir -p amazon-kinesis-video-streams-pic/build; cd amazon-kinesis-video-streams-pic/build; cmake ..

Step3: after that I clone c producer library from git url
    git clone --recursive https://github.com/awslabs/amazon-kinesis-video-streams-producer-c.git 

Step 4: And create a build directory and Execute CMake from it. 
	mkdir -p amazon-kinesis-video-streams-producer-c/build; cd amazon-kinesis-video-streams-producer-c/build; cmake ..

Step 5:- the c producer library compiled and after import in Xcode I got error like this “/Users/dreams/Desktop/KVS Live Demo/KVS Live Demo.xcodeproj Building for iOS Simulator, but the linked library 'libcproducer.dylib' was built for macOS.”

So I changed some lines in CMakeLists.txt file which is below 
	Before:- set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
	After: -  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -arch arm64")
After this change when I execute make command I got error  like “Architecture not supported ”
can you help me fix it?

**Comment by lherman-cs** [comment]
@dhruv-dhola I don't know much about iOS. But, from your logs, my guess is that you need to download and include iOS SDK. This way, you'll have the proper toolchain with the builtin frameworks for iOS and cross compilation support to arm64.

**Comment by lherman-cs** [comment]
Since the original issue has been answered, I'll mark this as resolved. Please feel free to open a new ticket for further assistance!

**Comment by SanthoshMKunthe** [comment]
I konw this is very simple and silly error. . . but i did not find solution anywhere. . . kindly help. . .

https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-c-test.html in run and verify section it says

```
mkdir -p amazon-kinesis-video-streams-producer-c/build; 
cd amazon-kinesis-video-streams-producer-c/build; 
cmake ..
```
upon doing this am getting the error as follows
```

PrivateNetwork:build excel$ clear

PrivateNetwork:build excel$ cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Applications/Xcode 11.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode 11.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Applications/Xcode 11.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/excel/Music/santhosh_m_kunthe/aws/amazon-kinesis-video-streams-producer-c/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_bdc09/fast && /Applications/Xcode 11.3.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_bdc09.dir/build.make CMakeFiles/cmTC_bdc09.dir/build
    make: /Applications/Xcode: No such file or directory
    make: *** [cmTC_bdc09/fast] Error 1
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/excel/Music/santhosh_m_kunthe/aws/amazon-kinesis-video-streams-producer-c/build/CMakeFiles/CMakeOutput.log".
See also "/Users/excel/Music/santhosh_m_kunthe/aws/amazon-kinesis-video-streams-producer-c/build/CMakeFiles/CMakeError.log".
PrivateNetwork:build excel$ 

```

**Comment by lherman-cs** [comment]
@SanthoshMKunthe It looks like there is problem with C compiler setup on your system. I'd highly recommend to simply create a hello world project with cmake, and see if cmake can detect your C compiler.
