### ISSUE TITLE
How to troubleshoot "Missing codec private data in fragment for track 1"

### ISSUE THREAD

**Issue by sairoop-elear** [awslabs/amazon-kinesis-video-streams-producer-c#110]
Hi There,
I'm using kinesis c producer to upload my video content into KVS and playback the content using DASH URL generated GetDASHStreamingSessionURL API. I'm seeing this odd behavior where it sometimes abruptly gives "Missing codec private data in fragment for track 1" error when I tried to generate a DASH URL despite of not getting any error while writing the frames into the C SDK.
According to my understanding, we don't provide any codec provide data for the default video track (track 1) which I didn't give. I pasted the kinesis logs below..
[storagelogs.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5160341/storagelogs.txt)

**Comment by MushMal** [comment]
@sairoop-elear the producer SDK can automatically extract the CPD for H264 and H265 only in the following cases:

* You have an actual H264 or H265 elementary stream with Annex-B format NALus.
* Your Idr frame has prepended SPS/PPS NALs (in case of H265 VPS/SPS/PPS).
* You have specified the NAL adaptation flags to adapt from Annex-B -> AvCC format in the code in StreamInfo.StreamCaps.
* The parsing/extraction didn't fail.

**Comment by MushMal** [comment]
Looking at the log I don't see any warnings about the parsing failure for CPD.

Check your media source and ensure it has the SPS/PPS NALs prepended to the IDR frame

**Comment by MushMal** [comment]
Resolving due to staleness
