### ISSUE TITLE
Uploading PCM audio

### ISSUE THREAD

**Issue by dwaynehubbard** [awslabs/amazon-kinesis-video-streams-producer-c#113]
Hello. 
  I'm attempting to use the AWS Kinesis video streams producer library to upload MKV files containing one (or two) PCM audio tracks. I have had to modify components of the producer and pic libraries to create the appropriate MKV file and it appears from the producer client side that I am successfully uploading raw Mu-Law audio chunks, but when I try to download the clip via the AWS dashboard I'm getting reports that no chunks were received. Is this possibly a dashboard limitation? Maybe I need a custom consumer to download this content? I would be happy to provide any information to continue debugging.

Regards,
Dwayne

**Comment by MushMal** [comment]
You don’t have to modify anything in pic to upload frames. What exactly did you need to modify? There is a small logic in the MKV generator that adds audio properties to the stream but it will depend on the downstream consumer if it needs it or not.

At any rate, if your fragments are not listed by ListFragment api then the upload is not successful.

In order to help, you will need to provide details about your scenario and the changes. Including debug or verbose logs from the producer and details about your consumer

**Comment by dwaynehubbard** [comment]
In the pic library I added some CODEC_ID definitions to video/mkvgen/Include.h

In the producer library I modified StreamInfoProvider.c's createAudioVideoStreamInfo() function to use a new createPcmMuLawAudioTrackInfo() function to specify new CODEC_ID and modify some track information for a MKV file containing two audio tracks.

Thanks for the tip on ListFragment, I'll see if the fragments are listed there. Will provide more details in a subsequent comment.  Thanks!

**Comment by MushMal** [comment]
Just a note that you don't need to modify any of the code. The default stream info returned from one of the helper stream info provide methods defined in the C SDK layer can be enhanced/amended to your needs. i.e. get the StreamInfo from the call to createDefaultStreamInfo and then add your track or change the track ID.

Getting back to the original question. Please enable debug logs by setting 

export AWS_KVS_LOG_LEVEL=2

and ensure your stream is being properly produced into the KVS backend.

Ensure you have the right region specified. 

Use ListFragment API to see whether you have the fragments in the list for the timerange you need

**Comment by MushMal** [comment]
Any further update? I would like to iterate as fast as possible and not let the issues go stale

**Comment by dwaynehubbard** [comment]
No, this issue can be closed. Thanks for your time.

**Comment by MushMal** [comment]
Perfect! Please don't hesitate to cut issues if you have any further questions.
