### ISSUE TITLE
Question: ^M

### ISSUE THREAD

**Issue by ycyang1229** [awslabs/amazon-kinesis-video-streams-producer-c#117]
Not sure it is because of my environment or it is the setting or this repo. I saw many files showing ^M. Is it possible to remove ^M? thanks.

**Comment by MushMal** [comment]
What do you mean by M^? Please clarify. If you are referring to something generating a file? Without further info this is not actionable and should be either closed or more details needed to understand the issue

**Comment by ycyang1229** [comment]
^M is CRLF, and it looks likes this repo uses CRLF not LF. Do I mistake it? I noticed this when I generated the patch for this sdk by using git format-patch and git am. thanks.

**Comment by ycyang1229** [comment]
If this repo uses CRLF and do not want to change it, I will try core.autocrlf. 
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf/20653073#20653073

**Comment by hassanctech** [comment]
It's not apparent that there is anything that needs to be done here.  If we can help with something please cut a new issue.

**Comment by ayazalavi** [comment]
@ycyang1229 @hassanctech Can you guys look at my issue https://github.com/aws-samples/amazon-kinesis-video-streams-webrtc-sdk-c-for-freertos/issues/23
