### ISSUE TITLE
Do AWS Kinesis Videostream MKV files conform to Matroska specification?

### ISSUE THREAD

**Issue by dwaynehubbard** [awslabs/amazon-kinesis-video-streams-producer-c#120]
The matroska.org "mkvalidator" tool generates many ERRORs when attempting to verify Matroska and WebM files for spec conformance.

Using the sample kvsAacAudioVideoStreamingSample with the KVS_DEBUG_DUMP_DATA_FILE_DIR environment variable exported, I run the sample like this:

$ ./build/kvsAacAudioVideoStreamingSample My-Kinesis-Videostream 20 samples/

and then when attempting to verify spec conformance using mkvalidator 0.5.2, I see the following output:

$ ../matroska.org/mkvalidator-0.5.2/release/gcc_linux_x64/mkvalidator My-Kinesis-Videostream_0.mkv 
ERR200: Missing element 'Targets' in Tag at 10246379
WRN801: The segment has no SeekHead section
ERR0B1: SimpleBlock at 119770 track #2 is not a keyframe
ERR0B1: SimpleBlock at 119808 track #2 is not a keyframe
ERR0B1: SimpleBlock at 135900 track #2 is not a keyframe
...<snipped similar messages>...
ERR0B1: SimpleBlock at 10228482 track #2 is not a keyframe
ERR0B1: SimpleBlock at 10246027 track #2 is not a keyframe
ERR0A2: The Cluster position 0 at 365 should be 305
ERR0A2: The Cluster position 0 at 950960 should be 950900
ERR0A2: The Cluster position 0 at 1898009 should be 1897949
...<snipped similar messages>...
ERR0A2: The Cluster position 0 at 7560524 should be 7560464
ERR0A2: The Cluster position 0 at 8450917 should be 8450857
ERR0A2: The Cluster position 0 at 9400193 should be 9400133
WRN800: The segment has Clusters but no Cues section (bad for seeking)
.       file "My-Kinesis-Videostream_0.mkv"
	created with Kinesis Video SDK 1.0.0 / Kinesis Video SDK 1.0.0

**Comment by MushMal** [comment]
KVS is using MKV as a packaging format. It only uses the minimal set of features from MKV.

You can use mkvinfo -v <file> to validate

I am not very familiar with mkvalidator tool.

Please resolve if you have no further questions on this

**Comment by dwaynehubbard** [comment]
Thanks for the explanation.
