### ISSUE TITLE
SignIn and stream using producer-C in Swift.

### ISSUE THREAD

**Issue by vaihsd** [awslabs/amazon-kinesis-video-streams-producer-c#125]
Am trying to use login credentials of 
https://console.aws.amazon.com/console/home?nc2=h_ct&src=header-signin 
in
 https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/IotAuthCallback.c -.-  Am using “abc@comp.com“ at Root user email address and “xyz” at password

Am doing this to use https://github.com/awslabs/amazon-kinesis-video-streams-producer-c inside Swift with intention of streaming and storing video from iOS device to Kinesis Video stream. 

a) Could someone kindly let me know where to pass “abc@comp.com“ & “xyz” -in- IotAuthCallback.c 
———i.e which C function to call from Swift to pass the argument/login credentials . 

b) Am trying to call C function “createRealtimeVideoStreamInfoProvider” from Swift code with intention of streaming and storing video from iOS device to Kinesis Video stream. 
———I have created a header for C function and added the header to Swift-Bridging-Header.h . Is this the proper way to do this. 
———i.e what is the proper way to call https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/f1313a6f71db36d38cb8ea605b810c2e197e84aa/src/source/StreamInfoProvider.c#L8 —from Swift —.

**Comment by girishalgundi** [comment]
hi @vaihsd .
Thanks for asking this question. As an iOS developer I was looking for its answer myself. @MushMal @lherman-cs kindly answer this question as this is going to help me and other iOS developers

**Comment by oceanvsagar** [comment]
And I also wonder how
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/f1313a6f71db36d38cb8ea605b810c2e197e84aa/src/source/StreamInfoProvider.c#L8
or
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/4bf15b655b19f72c90712ea2564e57f9989f01be/src/source/StreamInfoProvider.h#L70

connect to iOS/iPhone device camera. what is the code for that?

**Comment by MushMal** [comment]
I would like to add some clarity.

The iOS platform is not supported at this stage by the SDKs.

There is no support and will not be any support for username/password auth. The SDK at its core integrates with AWS credentials which are provided by the credential providers. There are few credential providers currently defined - Static, File and IoT. We will be adding more credential providers like Cognito but there is no ETA for that. So, if you need Cognito provider, you might need to implement it directly by following similar pattern as in IoT credential provider for example. C Producer has a set of helper APIs - for example createXXXStreamInfoProvider. The intent of these is to create a pre-configured StreamInfo structure which can be used directly or further modified to suit the application streaming needs. We don't have any integration with iOS media pipeline - it's up to the application to do so.

I would strongly recommend looking into the samples and the code. This is an open-source project and all of the code is public. There are few major points supporting iOS.

* Build: Including support for the toolchains (xCode) and the build of the dependent open source components such as openssl, libCurl, ..
* Integration with the iOS media pipeline. For this purpose, AV foundation classes can be used.

As we don't support iOS at this stage, there isn't much direct answers about the integration points that we can provide.

**Comment by MushMal** [comment]
I am going to close this issue as it's part of a larger enhancement of supporting iOS as a platform.
