### ISSUE TITLE
Unable to build C producer for Alpine musl 

### ISSUE THREAD

**Issue by sairoop-elear** [awslabs/amazon-kinesis-video-streams-producer-c#129]
I tried to compile KVS C producer sdk with my Alpine toolchain. There it seems like the open-source libraries fetched by KVS like SSL and Crypto are build for GLIBC instead of musl, Is there anything that seems wrong which I can fix in my Cmake file?

`/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libpthread.so.0, needed by ../open-source/lib/libssl.so, not found (try using -rpath or -rpath-link)`

`/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libc.so.6, needed by ../open-source/lib/libssl.so, not found (try using -rpath or -rpath-link)`

`/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libdl.so.2, needed by ../open-source/lib/libcrypto.so, not found (try using -rpath or -rpath-link)`

`../open-source/lib/libcrypto.so: undefined reference to 'fdopen@GLIBC_2.2.5'`

`../open-source/lib/libcrypto.so: undefined reference to 'mmap@GLIBC_2.2.5'`
`...`

**Comment by hassanctech** [comment]
We have a cross compile example for ARM in our Travis CI, see the relevant sections below, this should help you identify where to substitute your cross tool chain:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/.travis.yml#L102-L116

Let me know if you're still having issues?

**Comment by sairoop-elear** [comment]
Am not sure I conveyed my issue correctly. The issue that I'm facing is where I unable to figure out how c producer is building the open-source dependencies like ssl, crypto etc., with Alpine.
All I observed is that while building the producer library it's cloning, compiling, installing, and deleting the open-source dependencies where the end result is that the compilation was somehow done with GLIBC libraries but not with the muscl package used by Alpine. @hassanctech I'm new to CMake can you help me with that?

**Comment by MushMal** [comment]
Each of the dependent open-source project is getting build using it's own cmake with the helpers located here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/tree/master/CMake/Dependencies

We don't support this particular toolchain directly but you could modify the open source dependencies scripts or seek help in their respective forums for more info.

Please resolve this issue if you have no further questions about KVS itself
