### ISSUE TITLE
OOM crash in our ARM device

### ISSUE THREAD

**Issue by weijiazou** [awslabs/amazon-kinesis-video-streams-producer-c#142]
We used KVS to push audio and video streams on the ARM board. After running for a period of time (from a few minutes to about two hours), memory ran out and crashed.
Because memory is tight on our device, so the initialization StorageSize distribution only 1M of space, but as the lengthen of running time and memory will be slow to sustainable consumption, eventually crash because of insufficient memory.
May I ask if there are any parameters that can be adjusted for the memory tight environment, or have some suggestions for improvement? Thanks a lot!

The initialization information is as follows:
[16:15:54.514] 2020-11-27 08:18:02 INFO    heapInitialize(): Initializing native heap with limit size 1048576, spill ratio 0% and flags 0x00000001
[16:15:54.515] 2020-11-27 08:18:02 INFO    heapInitialize(): Creating AIV heap.
[16:15:54.525] 2020-11-27 08:18:02 INFO    heapInitialize(): Heap is initialized OK
[16:15:54.539] 2020-11-27 08:18:02 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000001, Next state: 0x0000000000000002
[16:15:54.548] 2020-11-27 08:18:02 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000010
[16:15:54.559] 2020-11-27 08:18:02 INFO    createDeviceResultEvent(): Create device result event.
[16:15:54.572] 2020-11-27 08:18:02 DEBUG   stepStateMachine(): State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000040
[16:15:54.573] 2020-11-27 08:18:02 INFO    createKinesisVideoStream(): Creating Kinesis Video Stream.
[16:15:54.580] 2020-11-27 08:18:02 DEBUG   logStreamInfo(): Kinesis Video Stream Info
[16:15:54.581] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Stream name: TTks0i2qfyu4_1 
[16:15:54.592] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Streaming type: STREAMING_TYPE_REALTIME 
[16:15:54.605] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Content type: video/h264 
[16:15:54.606] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Max latency (100ns): 85000000
[16:15:54.618] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Fragment duration (100ns): 20000000
[16:15:54.624] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Key frame fragmentation: Yes
[16:15:54.624] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Use frame timecode: Yes
[16:15:54.638] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Absolute frame timecode: No
[16:15:54.638] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Nal adaptation flags: 40
[16:15:54.647] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Average bandwith (bps): 2097152
[16:15:54.647] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Framerate: 25
[16:15:54.657] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Buffer duration (100ns): 100000000
[16:15:54.668] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Replay duration (100ns): 50000000
[16:15:54.668] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Connection Staleness duration (100ns): 50000000
[16:15:54.680] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Store Pressure Policy: 1
[16:15:54.693] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    View Overflow Policy: 1
[16:15:54.693] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Segment UUID: NULL
[16:15:54.706] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Frame ordering mode: 0
[16:15:54.706] 2020-11-27 08:18:02 DEBUG   logStreamInfo(): Track list
[16:15:54.707] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Track id: 1
[16:15:54.713] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Track name: kvs_video_track
[16:15:54.724] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Codec id: V_MPEG4/ISO/AVC
[16:15:54.725] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Track type: TRACK_INFO_TYPE_VIDEO
[16:15:54.739] 2020-11-27 08:18:02 DEBUG   logStreamInfo():    Track cpd: NULL

**Comment by hassanctech** [comment]
In addition to storage size there is also a buffer duration size.  How much memory do you have at your disposal?  It would be nice to know if you have limited bitrate set on your encoder to get an upper bound for how much memory can be used over a certain duration to pick buffer duration to match the max storage size you can support and set those values accordingly.

**Comment by MushMal** [comment]
To iterate on what @hassanctech mentioned. The main allocation the SDK is doing is around the content store and you can specify the size to use. There are also some auxiliary structures, the largest on being the content view. The logs with metrics printout should tell you exactly how many bytes are allocated for the content view but normally given the default configuration it's around 100K. 

There is a configuration that can ensure all of the allocations happen from within the content store but this will only work with platforms that have unaligned memory access allowed. If your platform supports unaligned memory then you can use 

`DEVICE_STORAGE_TYPE_IN_MEM_CONTENT_STORE_ALLOC`

in DeviceInfo.storageType.

This said, the networking in the C producer that's using libCurl, which, in turn is using openSSL allocate their own memory which will affect the overall working set.

Suggest running your streaming scenario, getting more info on the content view from the logs while running and look at the allocations via some platform specific tools like htop or similar to get some understanding of the memory usage overall for your process. Next, try to disable the network to ensure the content store fills up and puts the pressure on the memory. See how much memory you can allow for your application.

Please let us know how we can help.

P.S. Removing BUG tag.

**Comment by weijiazou** [comment]
@hassanctech @MushMal Thank you for your suggestions.

The memory of our device is only about 7M left, the video stream is about 900kbps, the buffer duration set 10 seconds, and the storage size set 2M.

For this test, I limited the network bandwidth to 1KB/s, and I choose default DEVICE_STORAGE_TYPE_IN_MEM storage type to send video data, the memory slowly decrease, and finally appear OOM crash. The device log please refer to B8_dev_1201_2040.zip, and the memory free value refer to B8_free_1201_2040.zip.

And I will do the same test by using DEVICE_STORAGE_TYPE_IN_MEM_CONTENT_STORE_ALLOC storage type.
Hope to get your response. Thank you!
[B8_dev_1201_2040.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5622893/B8_dev_1201_2040.zip)
[B8_free_1201_2040.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5622899/B8_free_1201_2040.zip)

**Comment by MushMal** [comment]
You must have a memory leak somewhere else in your system. Try running the video sample that comes with the repository. Make sure that it runs fine (with the modified memory/storage type).

**Comment by MushMal** [comment]
Looking at the second log I see you've specified max latency at 8.5 seconds. This is super aggressive for your network. You can't keep up streaming as is and the SDK reacts with the default callbacks to reset the stream and restart the stream that can cause a lot of openSSL and libCurl overhead.

Because you have a very aggressive temporal buffer, you only fill out about 77Kb of buffer.

We can't help debugging your application so I would suggest you use the stock application and only then start modifying it to your own needs. 

Please resolve this issue if you have no further questions regarding the KVS itself

**Comment by weijiazou** [comment]
@hassanctech I have tried the DEVICE_STORAGE_TYPE_IN_MEM_CONTENT_STORE_ALLOC storage type, but the OOM crash still exist.
As you mentioned, the SDK reacts with the default callbacks to reset the stream and restart the stream that can cause a lot of openSSL and libCurl overhead. How can I avoid this situation?

- Does the SDK have configuration to limit openSSL and libCurl memory usage? Is there any further confirmation that this is causing the memory consumption?
- I override the default callbacks? I found ClientCallbacks and StreamCallbacks have a lot of callbacks, which one or ones do I need to focus on?
- Or can be judged by the return value of putKinesisVideoFrame function?

I hope you can give me some advice. Thank you!

**Comment by MushMal** [comment]
@weijiazou the C Producer SDK uses the libCurl which in turn is using openSSL. There are few static crypto functions from OpenSSL that the C producer SDK common library is using but that's not creating any contexts. The SDK is using the library as is. There is little available to configure the footprint.

You could indeed change the behavior of the default callbacks if you wish. Take a look at the continuous retry logic in the C Producer.

As there is almost no information available for us, we can't guarantee that this is what's causing the issue. Nor we have access to your platform and tools. Try to debug your application directly. 

As suggested, use the unmodified video only sample from the C producer SDK. Make sure this works with your selection of the available memory. Then, try to adapt your application such that it works with your memory constraints.

**Comment by MushMal** [comment]
Please use this issue to track the OOMs on your platforms. 

We can't debug your application ourselves but could give you pointers to help.


As suggested:

* Run with DEVICE_STORAGE_TYPE_IN_MEM_CONTENT_STORE_ALLOC memory type in DeviceInfo.StorageInfo. This will make ALL of the allocations that the SDK itself is doing to go through the content store. This will ONLY work on platforms with unaligned memory access.
* Ensure you have not-very aggressive buffer duration and max latency settings. The continuous retry will reset the connection on buffer pressures. Initially, set these to 40 seconds and 30 seconds each. You can also try something larger to stabilize your platform.
* You can use instrumented memory allocators defined as a macro here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/utils/include/com/amazonaws/kinesis/video/utils/Include.h#L1399 You need to compile it with INSTRUMENTED_ALLOCATORS and ensure you call SET_INSTRUMENTED_ALLOCATORS first in your app and you can clear it later with RESET_INSTRUMENTED_ALLOCATORS call. You can track the overall memory consumption that ALL of the SDK is using by calling getInstrumentedTotalAllocationSize() API. IMPORTANT: This is about the allocations that the SDK itself is doing and does not track any allocations that libCurl and it's dependent libOpenSSL are doing.
* Use your favorite memory instrumentation tool to instrument the allocators for your process and dump the data.
* Configure your operating systems OOM killers preferences. NOTE: Most OOM killers work on system-wide basis and not on the process basis. Instrumenting or running tools on your platform to dump the overall top memory consumption can help you identify what's putting pressures on the system. For example, your process might consume lower memory and still get killed due to higher priority process or kernel requiring more memory. It also depends whether the OS deems your application as foreground or background. You should read up more on OOM killer for your OS.

**Comment by weijiazou** [comment]
@MushMal  Thank you for your reply!

I ran under CentOS using the same sample with the same speed limit of 1KBps, ran for 4 hours, and consumed about 10M memory.

In DEVICE_STORAGE_TYPE_IN_MEM storage type, Is it normal to consume this memory? How much memory is consumed in such a poor network environment?

**Comment by MushMal** [comment]
Your question is not as straight forward to answer as you might think.

* What do you mean by consumed memory? Are you talking about reserved or backed memory, private or shared bits? Normally, when we think about memory consumption, we should ensure we point what we mean. I would imagine you might be more interested in private bits which is on Linuxes called RSS memory.
* What tooling you use to get the information. Not all the tools give you adequate info. Try to use htop for example.
* What's consuming your memory. The SDK is just one part of the process.

DEVICE_STORAGE_TYPE_IN_MEM is the only supported mode currently for the content store. Content store is by far the largest consumer of the memory in the SDK itself but the content view and a few auxiliary allocations can also have a small impact. To tightly manage the memory, we have a flag DEVICE_STORAGE_TYPE_IN_MEM_CONTENT_STORE_ALLOC which would allow all of the allocations to be done from within the content store.

You can get more info from here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/structures.md

This said, we have no way of knowing how much the rest of your process is using. Those include allocations from your own application, your media pipeline, the networking stack (libCurl) and the openSSL. For that, you need to run with an instrumented allocators. There are few tools that you can use including valgrind, etc..

**Comment by weijiazou** [comment]
@MushMal Hello, MushMal, thanks very much for your information.
When we using this SDK in arm linux system. We refer to memory cost is RSS memory. On X86 linux we using ps command to see the sample process memory usage. On the arm device we use system command "echo 3 >/proc/sys/vm/drop_caches;free" to check memory left and hence compute the memory cost of the only active process  i.e. the kvs streaming sample process we are running.  When runing the KVS streaming sample the free memory will slowly decrease from 10 MBytes to 9, 8...., And then OOM .

We are generated the program(process) using only sample code  within sdk, and the sdk dependent libs are all system standard.   To us using this SDK and its related libs such as libCrul and openSSL, we take all these as SDK.

We need confirm if it is the fact that KVS SDK with openSSL and libCurl used, in the situation that network not stable, will cost  up to  6 or 8 or 10 MBytes memory.   And we should know how the memory is consumpted and if we can avoid using more memory than expected. 

Hope there could be optimization or sugguested action to reduce memoy consumption . Thanks.

**Comment by MushMal** [comment]
The KVS codebase itself can be controlled by the allocation size as I described above. I am not sure what's causing the memory pressure. I would recommend you to run it with larger memory footprint on a stock system and measure under the same network conditions whether the consumption tapers out. Meanwhile, you might also run valgrind or other instrumentation to see if you can see allocation hotspots.

We will also try to run some experimentation in the priority order but it's very different as we will not have the same setup.

**Comment by MushMal** [comment]
Any update on this issue? I would like to get more traction on this asap.

**Comment by MushMal** [comment]
@weijiazou We will be resolving if we won't hear back soon

**Comment by weijiazou** [comment]
@MushMal Thank you for your attention. 

I am so sorry! We are doing the same test on other ARM platforms these days. If there is any further information, I will timely inform you. let us keep in touch, thank you!

**Comment by hassanctech** [comment]
Resolving for now, feel free to re-open if you continue to see this issue.
