### ISSUE TITLE
[BUG]OOM crash using KvsVideoOnlyStreamingSample in my device

### ISSUE THREAD

**Issue by weijiazou** [awslabs/amazon-kinesis-video-streams-producer-c#146]
I used KvsVideoOnlyStreamingSample send video data on my device at a poor network environment.  The device has about 10M memory when the sample starts running, after running about 2 hours, memory ran out and crashed. 

I have made some minor changes to the parameters of the sample, please refer to the attachment for the source code. 

Is there a way to further locate the problem and suggest improvements? Thank you!

[KvsVideoOnlyStreamingSample.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5636276/KvsVideoOnlyStreamingSample.zip)

**Comment by MushMal** [comment]
Looks like you have already filed exact same issue https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/142

Please use that to track.

Resolving
