### ISSUE TITLE
The printed length and data type do not match

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-producer-c#148]
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/02118da186bfd9e7944ffe375acc003eeb224e2f/src/source/ContinuousRetryStreamCallbacks.c#L292

The type of statusCode is UINT32, but the printed type is long long.

Log:
```
continuousRetryStreamErrorReportHandler(): Reporting stream error. Errored timecode: 16076747225630000 Status: 0x66ac52000062
```

**Comment by MushMal** [comment]
It does look like an error. Do you want to push a PR for it? It should simply be 0x%08x
