### ISSUE TITLE
Can the audio support sampling rate 8k or 16k？

### ISSUE THREAD

**Issue by jackson-commit** [awslabs/amazon-kinesis-video-streams-producer-c#150]

**Comment by MushMal** [comment]
"Support" is a very wide term. What exactly do you mean? Your media pipeline might or might not support a particular audio sampling rate. The KVS SDK can support any frame rate as long as your CPU can keep up. The playback solution depends on your decoder and hardware.

In general, KVS streaming itself can support almost any format - even custom frames. The e2e media pipeline -> playback/consumer application might or might not support your media type.

Resolving as answered. Please cut a separate issue if you need detailed info.

**Comment by jackson-commit** [comment]
The AAC audio of our device does not currently support 48K sampling rate, but only supports 8K and 16K sampling rates. However, after successfully pushing 8K audio or 16 audio, your server has always failed to decode, so I want to get a clearer response. I want to know that our aac audio can be played on VLC media player, but the reason for the following error is always displayed when pushed to Amazon:
Fragment decoding error
An error occurred while decoding the media. Verify that the stream contains valid content
Believe in the content
Encoder ID:
acv1.64001e(H.264 High@3.0)
mp4a.40.2(AAC LC)

**Comment by MushMal** [comment]
@jackson-commit perhaps I should have been more clear. If you are using web playback (console or the HLS test page for example) then the decoding actually happens in your browser using browsers MSE. 

The console playback engine (or HLS/MPEG_DASH) will re-package the stream to MPEG. 

* Make sure your stream contains valid data. Try to stream audio only. Try to stream using sample pre-canned frames and ensure your browser is capable of the playback
* Make sure you specify the correct CPD. if you don't have the correct CPD for your audio track, you should use one of the helper methods in mkvgen package to generate it: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h#L615

If you have further issues with audio, contact your browsers manufacturer for more spec info
