### ISSUE TITLE
Handling stream errors

### ISSUE THREAD

**Issue by ronievron** [awslabs/amazon-kinesis-video-streams-producer-c#153]
Hi,

Is there a way to resubmit a clip that encountered a stream error on an initial attempt?
In the documentation I see a reference to
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kinesis_video_gstreamer_sample_app.cpp
But, this link does not exist.
Looking at the c++ gstreamer sample, the stream error handler just terminates the process.
The issue that I am facing is that when I send frames with a timestamp older then the most recent accepted frame, I see an error message stating that the timestamp is too old.
If I cannot resend old frames, how can I tell what is the time stamp of the most recent frame that was successfully received?

Thanks,

Roni

**Comment by MushMal** [comment]
Some samples are here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/tree/master/samples

We have a demo repository which has richer samples: https://github.com/aws-samples/amazon-kinesis-video-streams-demos

To dive deeper. The samples are using what's called Continuous Retry policy which would reset and retry on particular errors. There are errors which are recoverable and some that are not from the perspective of the core. The irrecoverable errors are for example auth errors. Recoverable are issues like networking. The higher-level policy resets the stream and restarts, potentially loosing the buffered data.

There are other class of issues related to media itself:

* PutFrame call fails for whatever reason - this means that the frame that was being produced fails and it will never be part of the stream. Investigate the reason.
* PutFrame succeeds but eventually after streaming the backend rejects it. Depending on the type of error ACK the underlying PIC logic might chose to "skip" over the "bad" fragment frames. Those are for example - "max duration reached" errors. In this case, the fragment is lost and retrying will not help.

The two issues just above are normally setup/bringup related and can be debugged and stabilized during the device bringup. Normally, they are related to bad encoder settings or some non-default settings in the KVS. These are not normal for production devices.

Please resolve if you have no further questions regarding this subject

**Comment by disa6302** [comment]
Closing based on tag.
