### ISSUE TITLE
[Help] How to turn off the compile warnings

### ISSUE THREAD

**Issue by yanjiesang** [awslabs/amazon-kinesis-video-streams-producer-c#158]
**How to turn off the following compile warnings**

#################################### Logging  Start ########################################
In file included from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/client/Include.h:14:0,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/include/../include/com/amazonaws/kinesis/video/webrtcclient/Include.h:18,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/source/Srtp/../Include_i.h:27,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/source/Srtp/SrtpSession.c:2:
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/PlatformUtils.h:24:24: warning: inline function ‘defaultLogPrint’ declared but never defined
 PUBLIC_API INLINE VOID defaultLogPrint(UINT32 level, PCHAR tag, PCHAR fmt, ...);
                        ^
In file included from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/client/Include.h:13:0,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/include/../include/com/amazonaws/kinesis/video/webrtcclient/Include.h:18,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/source/Srtp/../Include_i.h:27,
                 from /home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/src/source/Srtp/SrtpSession.c:2:
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:655:26: warning: inline function ‘defaultGetTime’ declared but never defined
 PUBLIC_API INLINE UINT64 defaultGetTime();
                          ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:623:14: warning: inline function ‘defaultDlError’ declared but never defined
 INLINE PCHAR defaultDlError();
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:622:14: warning: inline function ‘defaultDlSym’ declared but never defined
 INLINE PVOID defaultDlSym(PVOID handle, PCHAR symbol);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:621:14: warning: inline function ‘defaultDlClose’ declared but never defined
 INLINE INT32 defaultDlClose(PVOID handle);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:620:14: warning: inline function ‘defaultDlOpen’ declared but never defined
 INLINE PVOID defaultDlOpen(PCHAR filename, UINT32 flag);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:596:13: warning: inline function ‘defaultMemFree’ declared but never defined
 INLINE VOID defaultMemFree(VOID* ptr);
             ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:595:14: warning: inline function ‘defaultMemRealloc’ declared but never defined
 INLINE PVOID defaultMemRealloc(PVOID ptr, SIZE_T size);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:594:14: warning: inline function ‘defaultMemCalloc’ declared but never defined
 INLINE PVOID defaultMemCalloc(SIZE_T num, SIZE_T size);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:593:14: warning: inline function ‘defaultMemAlignAlloc’ declared but never defined
 INLINE PVOID defaultMemAlignAlloc(SIZE_T size, SIZE_T alignment);
              ^
/home/syj-ubuntu/SYJ/aws-kvs-webrtc-arm/AwsKVSWebRTC/open-source/pc/include/com/amazonaws/kinesis/video/common/CommonDefs.h:592:14: warning: inline function ‘defaultMemAlloc’ declared but never defined
 INLINE PVOID defaultMemAlloc(SIZE_T size);
              ^

**Comment by MushMal** [comment]
These are superfluous warnings related to inlining of the functions for perf purposes. Is there any reasons other than simply getting rid of warnings that you need? There are few possible ways to resolve them. You are welcome to try and send a PR

**Comment by disa6302** [comment]
@yanjiesang , 

I am closing this for now. We will work on getting rid of the warning as part of this [issue](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/354)

**Comment by lexi-brt** [comment]
@disa6302 I'm seeing these on a project I'm working on. I'd like to be able to do a clean build with no warnings. Is this possible to do with our dependency on kinesis? How can I get these to clear?
