### ISSUE TITLE
How to stream from webcam using amazon-kinesis-video-streams-producer-c

### ISSUE THREAD

**Issue by vijayrakesh13** [awslabs/amazon-kinesis-video-streams-producer-c#159]
Hi,

I'm able to run the sample application KvsAacAudioVideoStreamingSample.c streaming video from the files, but I want to stream video directly from a webcam, kindly, please suggest me.

Thanks,
Vijay

**Comment by vijayrakesh13** [comment]
Hi,

I saw streaming with webcam option is available with amazon-kinesis-video-streams-producer-CPP SDK using GStreamer plugin, but amazon-kinesis-video-streams-producer-c SDK supports same?

Thanks,
Vijay

**Comment by MushMal** [comment]
Sorry for the delay. You seem to confuse the media pipeline with the KVS sdk. CPP SDKs GStreamer plugin is based on cpp sdk which is a thin wrapper over the C sdk. You will need to use either some generic pipeline like GStreamer or your platform specific native methods of extracting video frames and encoding them prior submitting to the KVS sdk

**Comment by vijayrakesh13** [comment]
Thanks for the reply @MushMal. I'm getting started with KVS so, is there any example available in C or any documentation to use the GStreamer as a pipeline to KVS C SDK? My Intention is to stream video directly from webcam instead of file sources.

**Comment by MushMal** [comment]
The Cpp repository has an example of integrating cpp sdk directly with GStreamer. The gist is that both GStreamer and KVS at the core are c codebases. You can combine some of the GStreamer examples with the KVS sdk and n a way of getting the frames out of the media source and encoding and only then feeding the frames to KVS sdk. This said, your hardware could have its proprietary means of encoding frames

**Comment by vijayrakesh13** [comment]
Thank you! @MushMal

**Comment by vijayrakesh13** [comment]
Hi @MushMal, as there was no SDK for the Yocto project, I had downloaded all the .c and .h files and created an executable KvsAacAudioVideoStreamingSample, now I want to execute the below command in the terminal, but how to link GStreamer element kvssink to my executable?

$ gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name="YourStreamName" storage-size=512 access-key="YourAccessKey" secret-key="YourSecretKey" aws-region="YourAWSRegion"

Also, How to generate audio and video files with GStreamer as given in the sample application?

**Comment by disa6302** [comment]
Hello @vijayrakesh13 , 

Not sure what you mean? `gst-launch-1.0` is a command in itself and you can use it to try out different pipelines and narrow down to the pipeline that works best for your use case. 

You can look for reference pipelines [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/linux.md)

About how to generate the files, we do not have the command handy, but if you want to generate files and store in a directory and then reference from the application, `ffmpeg` is a good way to do it. You can look at https://avpres.net/FFmpeg/sq_H264.html. There is also a FFMPEG gstreamer plugin, though I am unsure about how it works. GStreamer forums are the best resource for the purpose.

**Comment by vijayrakesh13** [comment]
Hi @disa6302, I had tried this link, but I got an error as "no element kvssink". I had also added GST_PLUGIN_PATH to the sample application path as guided [here](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin.html).

Thanks for the information on FFMPEG. I guess the link you had shared is to transcode an image sequence into a video file, but I want to create h264 video frames and respective aac audio files from the webcam so that, I can upload them to KVS using the KvsAacAudioVideoStreamingSample application.

**Comment by disa6302** [comment]
@vijayrakesh13 ,

please ensure you run `cmake` with `-DBUILD_GST_PLUGIN=ON` option. Ensure it runs without errors and then export the path. The instructions should work as is. Please refer to some past questions in cpp SDK to understand what could be wrong with your build steps.

**Comment by vijayrakesh13** [comment]
@disa6302  As mentioned earlier, I compiled all .c and .h files to create the KvsAacAudioVideoStreamingSample application without using CMake because there was no eSDK readily available for the Yocto Project. In this case what changes I have to do?

**Comment by disa6302** [comment]
@vijayrakesh13 , 

I think you are confusing multiple things. If you want to use kvssink, you need to refer to the [CPP SDK](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp). Please look at how kvssink library is generated in cmake and try to reproduce the steps with Yocto. We do not have explicit support for Yocto nor have we tried it ourselves. As such, there is not much actionable here. I am closing this for now. I would suggest you to get started with the SDK on a Linux/Mac/Windows machine to get your feet wet before trying to integrate the SDK with Yocto.

**Comment by pestisid-cmd** [comment]
> Sorry for the delay. You seem to confuse the media pipeline with the KVS sdk. CPP SDKs GStreamer plugin is based on cpp sdk which is a thin wrapper over the C sdk. You will need to use either some generic pipeline like GStreamer or your platform specific native methods of extracting video frames and encoding them prior submitting to the KVS sdk

I am getting the input frames through ffmpeg instead of gstreamer. How can I exactly feed the KVS sdk exactly?
