### ISSUE TITLE
How to generate h264 video and AAC audio frames using FFMPEG

### ISSUE THREAD

**Issue by surya-teja-p** [awslabs/amazon-kinesis-video-streams-producer-c#163]
Hi,

What is the ffmpeg command to generate h264 video frames and aac audio frames from a video simultaneously, and what is the minimum & maximum duration of each frame?

Thanks & Regards,
Surya.

**Comment by disa6302** [comment]
@surya-teja-p ,

There should be resources online to answer this. Please go through how ffmpeg works. Also, you need to decide what the frame duration should be for your usecase. I am closing this because the question is not KVS specific.

**Comment by surya-teja-p** [comment]
@disa6302 

I want to live stream video and audio frames as soon as they are created without any delay. I'm approaching threading method, so that one thread will starting generating video and audio frames of 40ms, and other two threads will upload video and audio simultaneously.  Is this the correct method to do? Kindly please suggest me, I'm using KVS Producer C SDK.
