### ISSUE TITLE
Fragment decoding error

### ISSUE THREAD

**Issue by vijayrakesh13** [awslabs/amazon-kinesis-video-streams-producer-c#166]
Hi,

I'm trying to upload an audio and video stream to KVS which is generated using FFMPEG with the command, "ffmpeg -f alsa -i hw:0 -f video4linux2 -i /dev/video0 -c:a aac -t 0:10 -segment_time 00:00.040 -f segment audio_%003d.aac -c:v libx264 -t 0:10 -segment_time 00:00.040 -f segment out_%003d.h264". But I got a fragment decoding error while media playback on AWS. But sample audio and video provided in SDK plays fine, can you please tell me what I'm missing?
```
Codec ID:
avc1.64001e (H.264 High@3.0)
mp4a.40.2 (AAC LC)
Fragment number: 91343852333181531432836965621657777738834028213
Server timestamp: January 7, 2021 3:21:30 PM
Size: 951.9 KB

Fragment decoding error
There was an error decoding the media. Verify that the stream contains valid content.

Log:
2021-01-07 10:20:10 DEBUG   postWriteCallback(): Curl post body write function for stream with handle: teststream and upload handle: 0 returned: 
{"EventType":"RECEIVED","FragmentTimecode":1800,"FragmentNumber":"91343852333181531432836965621657777738834028213"}

2021-01-07 10:20:10 DEBUG   postWriteCallback(): Curl post body write function for stream with handle: teststream and upload handle: 0 returned: 
{"EventType":"BUFFERING","FragmentTimecode":3600,"FragmentNumber":"91343852333181531437788725778799303742890040337"}

2021-01-07 10:20:10 DEBUG   postWriteCallback(): Curl post body write function for stream with handle: teststream  and upload handle: 0 returned: 
{"EventType":"PERSISTED","FragmentTimecode":1800,"FragmentNumber":"91343852333181531432836965621657777738834028213"}

```
Thanks.

**Comment by disa6302** [comment]
@vijayrakesh13 , 

As the error suggests, there is something wrong with the content of the stream. First ensure you can play the video/audio files out to see if your ffmpeg command generated files in the correct format. Closing this because there is not much we can do from our side.
