### ISSUE TITLE
[QUESTION] How to create the sample frames ? 

### ISSUE THREAD

**Issue by ensean** [awslabs/amazon-kinesis-video-streams-producer-c#168]
A one liner description about the use case and what you are trying to achieve

** Logging ** 
Add relevant SDK logging. IMPORTANT NOTE: Please make sure to NOT share AWS access credentials under any circumstance! Please make sure they are not in the logs.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

I am wondering if it is possible to create my own sample frames, that is, is it possible to convert an mp4 video file to frames that can be consumed by the KVS c sdk?

**Comment by disa6302** [comment]
@ensean , 

You can. To do what you want, you can use a software such as GStreamer or ffmpeg. There should be some possible solutions online to do this. We do not have details in the SDK on the commands that were used.
