### ISSUE TITLE
[BUG] Cumulative increase in upload handles

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-producer-c#171]
**Describe the bug**
The number of upload handle is increasing, and the memory is used up.

**Steps**
1. When the stream state machine switches to STREAM_STATE_PUT_STREAM, it will create  a new request curl. The pCurlRequest->uploadHandle will increase by 1. At the same time, a new thread1 will be created.
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/38380a44664b67bc2db110b5f2543d05e6bc0e59/src/source/CurlApiCallbacks.c#L2110-L2111

2. Once streamFragmentErrorAck is called, it will reset the stream machine in streamTerminatedEvent. The pCurlRequest->uploadHandle will increase again and thread2 will be created.
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/988b1ab392b50f0ad573cc1a7183299f08425597/src/client/src/Stream.c#L2721

3. When thread2 exits, streamTerminatedEvent will be called, and reset the stream machine again, it will destroy thread2 and create thread3 for putStreamCurlHandler.

4. If step2 occurs several times, there will be several upload handles and threads.  At the same time, the created thread will take up a lot of memory.

Since 2021-01-09 07:28:31, streamFragmentErrorAck was called 38 times. oom-killer happends at 07:30:47.
```
15:30:49  [ 2346.990000] 195TimerManager invoked oom-killer: gfp_mask=0xd0, order=1, oom_adj=0, oom_score_adj=0
```
By searching _create thread putStreamCrulHandler_ and _Network thread for Kinesis Video stream:_. We can find that, 
before uploadHandle=376 is created, the last exited handle is 339, total number is 376-339=37.

```
15:30:43  2021-01-09 07:30:43 WARN    putStreamCurlHandler(): Network thread for Kinesis Video stream: UB3Ve2Pc2P3S10 with upload handle: 339 exited. http status: 0

15:30:43  2021-01-09 07:30:43 WARN    putStreamCurl(): create thread putStreamCrulHandler, pCurlRequest=291bed4. uploadHandle=376
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20633988/104164558-09d5bd80-5433-11eb-96fc-d998542cdd92.png)
![image](https://user-images.githubusercontent.com/20633988/104164615-21ad4180-5433-11eb-9541-99cff926ddeb.png)

**Logging**
[session_ch34 (com7)_0109_145136.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/5794757/session_ch34.com7._0109_145136.log)

**Comment by MushMal** [comment]
This is not a leak nor a bug but the implementation handling of a particular edge case. There is no memory leak but an increase in the overall SDK work-set. I would rather treat this as a feature request to drive the C producer network liveness via a fixed thread pool rather than each with its own thread.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/172

**Comment by MushMal** [comment]
For the purposes of this issue, I would recommend focusing on remedying the temporary work-set increase issue.

What's causing the error ACK in your case? Knowing how to keep the upload handles to the minimum will decrease the workset

**Comment by Nomidia** [comment]
Ok, we will focus on streamFragmentErrorAck.

**Comment by disa6302** [comment]
Closing assuming question answered.
