### ISSUE TITLE
DescribeStreamCurlHandler fails

### ISSUE THREAD

**Issue by surya-teja-p** [awslabs/amazon-kinesis-video-streams-producer-c#189]
Hi,

When I use Access Key, Secret key and Session token from AWS Credential provider(alias role) I got below error, I'm using AmazonRootCA certificate provided by AWS. I'm getting this error specifically on my embedded target board. If I don't use temporary keys and give permanent account keys, it works fine.   

curlCompleteSync(): curl perform failed for url https://kinesisvideo.us-east-1.amazonaws.com/describeStream with result SSL peer certificate or SSH remote key was not OK: server certificate verification failed. CAfile: AmazonRootCA1.pem CRLfile: none
2021-01-29 10:26:52 WARN    curlCompleteSync(): HTTP Error 0 : Response: (null)
Request URL: https://kinesisvideo.us-east-1.amazonaws.com/describeStream

**Comment by MushMal** [comment]
This doesn't really make sense. From the perspective of curl, there is absolutely no difference whether you are using session token or not - that's a higher-level concept whereas your failure is at a low-level TLS.

I would recommend debugging your solution further and ensure the Amazon public cert is used with your application. Ensure you've copied https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/tree/master/certs to your public CA cert store.

**Comment by MushMal** [comment]
Any updates? Would not want this issue to go stale and get closed

**Comment by surya-teja-p** [comment]
Thanks, it worked. Earlier I was using IoT Core CA Certificate, but it worked on Ubuntu 18.04 LTS.
