### ISSUE TITLE
[QUESTION] Which callback can hookup The security token included in the request is expired error 

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-c#198]
Sometimes security token is expired and not sure what happen, want to know which callback is trigger by this error,
we try to restart our application when this error happen. 

** Logging ** 
35726:[2021-02-22 19:01:08.160] 2021-02-22 11:00:04 ERROR   kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000051
35727:[2021-02-22 19:01:08.332] 2021-02-22 11:00:04 WARN    postWriteCallback(): Failed to submit ACK: {"message":"The security token included in the request is expired"} with status code: 0x52000051
35910:[2021-02-22 21:01:06.333] 2021-02-22 13:00:02 ERROR   kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000051
35911:[2021-02-22 21:01:06.517] 2021-02-22 13:00:02 WARN    postWriteCallback(): Failed to submit ACK: {"message":"The security token included in the request is expired"} with status code: 0x52000051
35923:[2021-02-22 22:01:06.628] 2021-02-22 14:00:02 ERROR   kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000051
35924:[2021-02-22 22:01:06.628] 2021-02-22 14:00:02 WARN    postWriteCallback(): Failed to submit ACK: {"message":"The security token included in the request is expired"} with status code: 0x52000051
35936:[2021-02-22 23:01:06.913] 2021-02-22 15:00:02 ERROR   kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000051
35937:[2021-02-22 23:01:06.913] 2021-02-22 15:00:02 WARN    postWriteCallback(): Failed to submit ACK: {"message":"The security token included in the request is expired"} with status code: 0x52000051
35962:[2021-02-23 09:01:06.752] 2021-02-23 01:00:02 ERROR   kinesisVideoStreamParseFragmentAck(): operation returned status code: 0x52000051
35963:[2021-02-23 09:01:06.938] 2021-02-23 01:00:02 WARN    postWriteCallback(): Failed to submit ACK: {"message":"The security token included in the request is expired"} with status code: 0x52000051

[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6026431/log.txt)

**Comment by disa6302** [comment]
@henryChmn , 

You can listen to fragment Ack using [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/58e1c6a1cb191f947d904784503b506e04525682/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L211) callback. The ACK types are defined [here](https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/fd141e01cacfa063e5c6846593733613cce6cebd/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L752).
