### ISSUE TITLE
About KVS C Producer Library

### ISSUE THREAD

**Issue by Zevolusion** [awslabs/amazon-kinesis-video-streams-producer-c#202]
1、在海思平台的摄像头上测试，按原文档编译生成的可执行文件kvsVideoOnlyStreamingSample是无法在摄像头上运行的
2、现需要将C Producer 编译器改成海思SDK提供的arm-himix100-linux-gcc编译器重新编译

请问如何修改makefile，或者有其他解决方案
I need Chinese

**Comment by disa6302** [comment]
@Zevolusion ,

Not sure what you mean. But can you elaborate in English?

**Comment by hassanctech** [comment]
Results from Google Translate:

1. Tested on the camera of the HiSilicon platform, the executable file kvsVideoOnlyStreamingSample compiled according to the original document cannot be run on the camera
2. Now you need to change the C Producer compiler to the arm-himix100-linux-gcc compiler provided by HiSilicon SDK to recompile

How to modify the makefile, or have other solutions

-----

We have an example in our Travis CI to show the cross compile for your compiler:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/.travis.yml#L115-L129

**Comment by hassanctech** [comment]
Closing this due to staleness.  If you still need help please open a new issue.  Thank you.
