### ISSUE TITLE
[QUESTION]{"EventType":"ERROR","ErrorCode":"INVALID_MKV_DATA","ErrorId":4006} frequency happen with same Timestamp 

### ISSUE THREAD

**Issue by henryChmn** [awslabs/amazon-kinesis-video-streams-producer-c#209]
We are seeing the retry error a lot with same timestamp, maybe we can reduce it.

** Logging ** 
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/6302898/log.txt)

**Comment by hassanctech** [comment]
Which version of the SDK are you running?

**Comment by henryChmn** [comment]
@hassanctech cproducer SDK version: v1.1.1

**Comment by henryChmn** [comment]
@hassanctech 
![image](https://user-images.githubusercontent.com/58592084/117092222-3fab0300-ad90-11eb-8a05-1e842841a927.png)

**Comment by henryChmn** [comment]
@hassanctech 
![image](https://user-images.githubusercontent.com/58592084/117092704-9ebd4780-ad91-11eb-8109-16032b657a1a.png)

**Comment by henryChmn** [comment]
@hassanctech 
If I not stop stream handle, it can keep 24 hours to upload, right  ? and I need create new stream handle every 24 hours.

**Comment by hassanctech** [comment]
Yes that is correct.

**Comment by disa6302** [comment]
Closing due to no traction.Feel free to reopen if there is anything to discuss.
