### ISSUE TITLE
[QUESTION] Curl Issue using createDefaultCallbacksProviderWithIotCertificate

### ISSUE THREAD

**Issue by karan-nd** [awslabs/amazon-kinesis-video-streams-producer-c#211]
Unable to authenticate with createDefaultCallbacksProviderWithIotCertificate api. 
**However, the same api, library (libcproducer.so )& certificates work with the Kinesis test app**

Curl error reason is not clear, hence not able to pin-point the issue

** Logging ** 

```
ERROR   blockingCurlCall(): Curl perform failed for url https://url/role-aliases/KvsCameraIoTRoleAlias/credentials with result Problem
 with the local SSL certificate : could not load PEM client certificate, OpenSSL error error:00000000:lib(0):func(0):reason(0), (no key found, wrong pass phrase, or wrong file format?)

Failed with status 0x15000011
```

**Comment by disa6302** [comment]
Closing due to no response. Feel free to reopen when you have some logs to share.
