### ISSUE TITLE
[QUESTION] new develop

### ISSUE THREAD

**Issue by matiasechaharria** [awslabs/amazon-kinesis-video-streams-producer-c#216]
Hello, I am about to start a new development on a proprietary hardware that runs an android oreo and I wonder which sdk is the appropriate one for it.
Will this sdk continue to be supported? Will new functionalities be implemented?

**Comment by hassanctech** [comment]
We do not have any plans to stop supporting this SDK.  In the future it's possible it could move to a different repository but in some shape or form we will have a producer SDK.

If your goal is to send video to Kinesis Video Streams to be persisted for later or real time retrieval by a consumer then this is the right SDK.

The samples will show how to use it, here is the video only sample:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsVideoOnlyStreamingSample.c

There is a lower level platform independent library called the PIC which has APIs that you will call, one of them is `putKinesisVideoFrame`.  You will need to integrate with your media/encoder pipeline that produces the frames and send them to KVS via the put `putKinesisVideoFrame` API.  

Yes we plan to continue updating and supporting this SDK.

If you need help we can walk through cross compiling these libraries for your target platform to start with you'll need your toolchain.  If you look at our CI we actually test the cross compile, you can tweak this to your specify toolchain:  

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/.travis.yml#L115-L129

**Comment by disa6302** [comment]
Closing assuming question is answered.
