### ISSUE TITLE
[QUESTION] createKinesisVideoStreamSync Failed with status 0x0000000f 

### ISSUE THREAD

**Issue by mechavarriahipcam** [awslabs/amazon-kinesis-video-streams-producer-c#218]
Hello,
I'm trying to stream to kinesis using the cross-compiled sdk-c sample for aarch64-linux-andoid.
Running the program as a console app correctly sends the frames but, when I use the same program from a JNI in the andoid studio, it gives an time out error in createKinesisVideoStreamSync(clientHandle, pStreamInfo, &streamHandle));.

Why time out is generated??

LOGS:
this is the log I get
Stream Credencials
/*---------------------------*/
streamName: VDC 
accessKey: accessKey
secretKey: secretKey
cacertPath: (null) 
sessionToken: (null) 
region: us-east-1 
data.sampleDir: / system / priv-app / kinesis / samples
/*----------------------------*/
Loading audio frames ...
Done loading audio frames.
Loading video frames ...
: Done loading video frames.
 streaming for 10 seconds
 streamStopTime: 1820521347
 Hipcam_KinesisVideoStream: createRealtimeAudioVideoStreamInfoProvider OK
 set up audio cpd OK
generate audio cpd OK
createStreamCallbacks OK
createStreamCallbacks OK
createKinesisVideoClient OK
/ * ------------------------- ------------------------------------------- * /
 clientHandle: 0.000000
 pStreamInfo:
 pStreamInfo-> version: 2
 pStreamInfo-> name: VDC
 pStreamInfo-> tagCount: 0
 pStreamInfo-> retention: -1014444032
 pStreamInfo-> kmsKeyId:
 pStreamInfo-> streamCaps.contentType: 1405232428
pStreamInfo-> streamCaps.maxLatency: 1020000000
: pStreamInfo-> streamCaps.adaptive: 1
 pStreamInfo-> streamCaps.maxLatency: 1020000000
pStreamInfo-> streamCaps.fragmentDuration: 20000000
pStreamInfo-> streamCaps.keyFrameFragmentation: 1
pStreamInfo-> streamCaps.frameTimecodes: 1
pStreamInfo-> streamCaps.fragmentAcks: 1
 pStreamInfo-> streamCaps.recoverOnError: 1
pStreamInfo-> streamCaps.nalAdaptationFlags: 40
pStreamInfo-> streamCaps.avgBandwidthBps: 2097152
pStreamInfo-> streamCaps.frameRate: 120
pStreamInfo-> streamCaps.connectionStalenessDuration: 50000000
pStreamInfo-> streamCaps.timecodeScale: 10000
pStreamInfo-> streamCaps.recalculateMetrics: 1
pStreamInfo-> streamCaps.segmentUuid: 0
pStreamInfo-> streamCaps.trackInfoCount: 2
streamHandle: 0 
/*--------------------------------------------------------------------*/
Failed with status 0x0000000f -----> #define STATUS_OPERATION_TIMED_OUT           STATUS_BASE + 0x0000000f

**Comment by disa6302** [comment]
@mechavarriahipcam ,

I suspect Curl timeout issues or network. Please debug your network settings. 

Please open a new issue and attach some logs if you are still facing issues.
