### ISSUE TITLE
[BUG] Failed to submit auto eofr with 0x32000002

### ISSUE THREAD

**Issue by schultetwin1** [awslabs/amazon-kinesis-video-streams-producer-c#228]
**Media pipeline:**
 - Media source is custom
 - Video codec: "h264"
 - Audio codec : "alaw" 
 - Intermittent streaming with auto eofr

**Logging**
```
putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x32000002 decoding timestamp: 0 presentation timestamp: 0
checkIntermittentProducerCallback(): Failed to submit auto eofr with 0x32000002, for stream name: 86b908c73530b14f1070d54ec897705d303aaf96d6828fd092d30db55e8a264a
checkIntermittentProducerCallback(): operation returned status code: 0x32000002
timerQueueExecutor(): operation returned status code: 0x32000002
```

After this failure occurs, subsequent frame uploads also appear to fail.

**Describe the bug**
For some reason, we are validating the mkv frame of a EOFR frame.

**SDK version number**
1.1.1

**To Reproduce**
We unfortunately do not have reproduction steps, just logs from customers who are missing their videos.

**Expected behavior**
The auto-eofr frame should upload successfully.

**Notes**
I'm kind of stumped as to why this would happen. Here is the stack trace for what would cause this:

```
mkvgenValidateFrame(PStreamMkvGenerator pStreamMkvGenerator, PFrame pFrame, PTrackInfo pTrackInfo, PUINT64 pPts, PUINT64 pDts, PUINT64 pDuration, PMKV_STREAM_STATE pStreamState
mkvgenPackageFrame(PMkvGenerator pMkvGenerator, PFrame pFrame, PTrackInfo pTrackInfo, PBYTE pBuffer, PUINT32 pSize, PEncodedFrameInfo pEncodedFrameInfo)
# THIS IS WEIRD. Why are we calling mkgvenPackageFrame, it should not be called due to an if statement 
putFrame(PKinesisVideoStream pKinesisVideoStream, PFrame pFrame)
frameOrderCoordinatorPutFrame(PKinesisVideoStream pKinesisVideoStream, PFrame pUserFrame)
putKinesisVideoFrame(STREAM_HANDLE streamHandle, PFrame pFrame)
checkIntermittentProducerCallback(UINT32 timerId, UINT64 currentTime, UINT64 customData
```

There is a chance this is due to stack corruption of the `eofr` variable, but I can't find where that would occur.

**Comment by hassanctech** [comment]
While I look into this, question, have you tried it with the latest release 1.2.0 to see if you still see the issue?

**Comment by disa6302** [comment]
@schultetwin1 , 

Do you have an update?

**Comment by hassanctech** [comment]
@schultetwin1 From our side we've had a look at the updates that went in from 1.1.1 to 1.2.0 and there were enough PIC layer changes that could have impacted this so I would ask you to please try with 1.2.0 and see if the issue goes away.

**Comment by schultetwin1** [comment]
@disa6302, we are going to roll out the 1.2.0 to our devices in the next couple weeks, but since we can not reproduce this issue locally we are not able to determine if 1.2.0 will change any behavior.

As I mentioned to @hassanctech, I have also looked over the changes in the PIC layer. I did NOT see any changes that would have fixed a bug that could cause this issue. For that reason, unless you can point to a specific commit that would have fixed this issue I don't think we should assume this issue is fixed.

**Comment by hassanctech** [comment]
I did trace the code and I do not see any way this can happen either other than that eofr variable somehow getting modified I just can't see how that would happen.  I've tried to build with `-fstack-protector-all` and I still did not hit the issue in our tests.  @schultetwin1 do you have libssp on your platform available so that you could try that flag as well, you're probably familiar with this already it'll just add a guard band around the stack allocation and if it's modified it'll crash the program so it might help determine where this is happening.

On a side note when I've seen this happen in the past is when structure sizes are different in the library you're linking against at runtime vs what you compiled with, is there any chance there could be a mismatch between what you have on your devices and how they were build?  Perhaps you could do a quick md5sum check on the binaries you build and what's actually on the device (it's possible the md5sum is different due to things like different rpath embedded in the library, etc.).

**Comment by schultetwin1** [comment]
@hassanctech - Thank you so much for running that testing!

> @schultetwin1 do you have libssp on your platform available so that you could try that flag as well, you're probably familiar with this already it'll just add a guard band around the stack allocation and if it's modified it'll crash the program so it might help determine where this is happening.

That's a good idea, we can add stack protection to at least crash if we detect this issue. We have a way to collect core dumps which we can use to determine if this crash is happening.

We are also moving away from using the auto EOFR and instead sending the EOFR ourselves, so this code path is not going to be hit by our code path.

Since we would need to reproduce on our devices and we have changed our code path, I'm going to close this issue out for now.

Thank you again @hassanctech!

**Comment by schultetwin1** [comment]
> That's a good idea, we can add stack protection to at least crash if we detect this issue. We have a way to collect core dumps which we can use to determine if this crash is happening.

Just following up here with a correction. It turns out the toolchain we are using was compiled with `--disable-libssp`. So unfortunately, we can't enable stack protection :(. But we can at least enable it in our test code and see if something pops up.
