### ISSUE TITLE
G711 audio format sample and test guide.

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#230]
I try to finalize a audio&video sample with G711 audio format:
https://github.com/awsa2ron/amazon-kinesis-video-streams-producer-c/tree/g711-alaw

putMedia succeeded, but playback failed, either aws console nor test page. 
Error is:
```
AAC CPD must be of length 2 or 5, but was 18."
```

**Comment by disa6302** [comment]
Closing this as duplicate of #229
