### ISSUE TITLE
how to create provider by using iot credential

### ISSUE THREAD

**Issue by Kelephant** [awslabs/amazon-kinesis-video-streams-producer-c#232]
I want to use iot credentials to create providers for kvs and webrtc, what should I do? Is there any demo for reference ?

**Comment by jdelapla** [comment]
Perhaps the sample in our webrtc SDK would help act as a reference?
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L707
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L738

**Comment by disa6302** [comment]
@Kelephant ,

You can also follow the demos [here](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/canary/producer-c#using-iot-credential-provider) that uses IoT with producer SDK.
