### ISSUE TITLE
[QUESTION]the device report 0x15000011 error code after IOT reconnected successfully

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-producer-c#238]
Heres two question：
Q1、The debug log shows that  iot reconnected successfully,  webrtc  reconnected successfully using same cert params, why func createKinesisVideoStream report 0x15000011 error code ?
Q2、func createKinesisVideoStream keep report 0x5200000e  error code after iot fail，Is there any other way to modify the timeout threshold（ 3000 milliseconds ） to enhance reconnection ability?

heres log info：
[0m[32;1m[2021/08/30 00:39:53:3145] I: lws_role_call_alpn_negotiated: 'http/1.1'
[0m[32;1m[2021/08/30 00:39:53:3147] I: lws_tls_session_new_mbedtls: [wsicli|2ef|WS/h1/m-f3e86af6.kinesisvideo.us-east-2.amazonaws.]: reuse default_m-f3e86af6.kinesisvideo.us-east-2.amazonaws.com_443, (default:2)
[0m[32;1m[2021/08/30 00:39:53:3147] I: client connect OK
[0m[32;1m[2021/08/30 00:39:53:3149] I: lws_http_client_socket_service: HANDSHAKE2: [wsicli|2ef|WS/h1/m-f3e86af6.kinesisvideo.us-east-2.amazonaws.]: sending headers (wsistate 0x10000204), w sock 55
[0m[32m[08:39:53.541 info AWS_Record 748 Aws_record.c:456]aws Cloud init already with Flag[1]
[0m
[32;1m[2021/08/30 00:39:53:6748] I: lws_client_ws_upgrade: WSI_TOKEN_PROTOCOL is null
[0m[32;1m[2021/08/30 00:39:53:6750] I: __lws_header_table_detach: [wsicli|2ef|WS/h1/m-f3e86af6.kinesisvideo.us-east-2.amazonaws.]: ah 0x9b2b48 (tsi=0, count = 1)
[0m[32;1m[2021/08/30 00:39:53:6751] I: __lws_header_table_detach: nobody usable waiting
[0m[32;1m[2021/08/30 00:39:53:6752] I: _lws_destroy_ah: freed ah 0x9b2b48 : pool length 0
[0m[32;1m[2021/08/30 00:39:53:6753] I: __lws_header_table_detach: [wsicli|2ef|WS/h1/m-f3e86af6.kinesisvideo.us-east-2.amazonaws.]: ah 0x9b2b48 (tsi=0, count = 0)
[0m[32m[08:39:53.675 info AWS_Media 3491 Aws_media.c:357]Signaling client state changed to 9 - 'Connected'[0m

[32m[08:44:20.893 info Encrypt-Ssl 765 Ssl.c:658]_Encrypt_MbedSslHandshake, ssl:0xc7f550[0m
[32m[08:44:20.967 info Encrypt-Ssl 765 Ssl.c:673]hostname=dev.roohq.com[0m
[33m[08:44:20.967 warn Encrypt-Ssl 765 Ssl.c:696]kidy: _Encrypt_MbedSslHandshake want read, returned:ffff9700, fd 58, in_msg[0] = 0.[0m
[32m[08:44:21.229 info Encrypt-Ssl 765 Ssl.c:658]_Encrypt_MbedSslHandshake, ssl:0xc7f550[0m
[32m[08:44:21.230 info Encrypt-Ssl 765 Ssl.c:673]hostname=dev.roohq.com[0m
2021-08-30 00:44:21 ERROR   blockingCurlCall(): Curl perform failed for url https://c1ql9jugg502at.credentials.iot.us-east-2.amazonaws.com/role-aliases/Ranger-role-dev-alias/credentials 
with result Timeout was reached : Resolving timed out after 3000 milliseconds 
2021-08-30 00:44:21 ERROR   createKinesisVideoStream(): operation returned status code: 0x15000011
2021-08-30 00:44:21 ERROR   createKinesisVideoStreamSync(): operation returned status code: 0x15000011

2021-08-30 00:44:21 ERROR   createKinesisVideoStream(): operation returned status code: 0x5200000e
2021-08-30 00:44:21 ERROR   createKinesisVideoStreamSync(): operation returned status code: 0x5200000e

[error.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/7075265/error.txt)

**Comment by MushMal** [comment]
These are different endpoints. You might want to debug this a little further to understand why the call to IoT fails with a timeout.

You can increase the timeout value if you want. It must be somewhere in the headers. Perhaps someone from AWS can point out.

**Comment by August88618** [comment]
@MushMal , ths for your reply, that is an occasional problem and  according to the debug log, when the first createKinesisVideoStream  requst report status with 0x1500000011 error code, the later createKinesisVideoStream requst will continue report 0x5200000e and that will last dozens of minutes. 
I just wonder is there any way to fix this problem and how to reset the wrong stream status of this problem?

**Comment by MushMal** [comment]
0x5200000e is the invalid state machine state status indicating that the operations are not permitted. This kind of makes sense as you need to get the access token first in order to proceed. I am just not sure why your IoT credential provider fails. Try to debug this further by running on a commodity platform (Linux on PC for example) and get verbose logs printed. Make sure you have the selection of the closest region to you and a good network. Remove any customizations from your code other than the IoT usage.

**Comment by disa6302** [comment]
@August88618 , 

Based on the recommendations provided, I am closing this issue. Please feel free to reopen the issue with VERBOSE logs if your issue is unresolved
