### ISSUE TITLE
[QUESTION]Which API interface I can obtain the length of the uploaded MKV media file and whether it is successful?

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-producer-c#248]
Q:which API interface I can obtain the length of the uploaded MKV media file and how to get the upload result?

**Comment by MushMal** [comment]
Hard to guess what exactly your question is about. If you are asking about the current buffer information on the client SDK side then you can call getKinesisVideoStreamMetrics specified here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L2086

The Stream metrics contain the window duration and overall duration. The duration is the amount of buffer (in 100ns units) that has not yet been streamed. The overall duration is the entire buffer duration - including not yet streamed plus the data that was streamed but not yet ACK-ed. There are similar fields for the byte size of the buffer.


If you refer to the backend API then you can call the ListFragments API to get more info. https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_ListFragments.html

**Comment by hassanctech** [comment]
@August88618 is your question answered?

**Comment by disa6302** [comment]
Closing assuming question is answered.
