### ISSUE TITLE
[QUESTION]: Undefined Symbols in the static library of cproducer.

### ISSUE THREAD

**Issue by stardevrk** [awslabs/amazon-kinesis-video-streams-producer-c#252]
I am building this library on the mac machine. I followed the steps on the ReadMe file. I added -DBUILD_STATIC=ON for the static library build. All sample files are built and they are working well.
But when I use a libcproducer.a file in the other project, it shows the undefined symbols for many functions.
What is the solution for CMAKE? Or LINKER?

** Logging ** 
This shows some of logs.
`"_curl_easy_strerror", referenced from:
      _curlCompleteSync in libcproducer.a(Response.c.o)
  "_getServiceCallResultFromHttpStatus", referenced from:
      _curlCompleteSync in libcproducer.a(Response.c.o)
  "_curl_easy_pause", referenced from:
      _terminateCurlSession in libcproducer.a(Response.c.o)
      _notifyDataAvailable in libcproducer.a(Response.c.o)
  "_curl_slist_free_all", referenced from:
      _closeCurlHandles in libcproducer.a(Response.c.o)
  "_curl_easy_cleanup", referenced from:
      _closeCurlHandles in libcproducer.a(Response.c.o)
  "_stackQueueFree", referenced from:
      _freeCurlRequest in libcproducer.a(Request.c.o)
  "_getKinesisVideoStreamData", referenced from:
      _postReadCallback in libcproducer.a(Response.c.o)
  "_curl_easy_init", referenced from:
      _initializeCurlSession in libcproducer.a(Response.c.o)
  "_requestRequiresSecureConnection", referenced from:
      _initializeCurlSession in libcproducer.a(Response.c.o)
  "_trimstrall", referenced from:
      _writeHeaderCallback in libcproducer.a(Response.c.o)
  "_stackQueueEnqueue", referenced from:
      _writeHeaderCallback in libcproducer.a(Response.c.o)
  "_curl_easy_perform", referenced from:
      _curlCompleteSync in libcproducer.a(Response.c.o)
  "_createFile", referenced from:
      _createCurlResponse in libcproducer.a(Response.c.o)
     (maybe you meant: _createFileAuthCallbacks)
  "_removeRequestHeaders", referenced from:
      _freeCurlRequest in libcproducer.a(Request.c.o)
  "_freeStaticCredentialProvider", referenced from:
      _freeStaticAuthCallbacks in libcproducer.a(StaticAuthCallbacks.c.o)
  "_createStaticCredentialProvider", referenced from:
      _createStaticAuthCallbacks in libcproducer.a(StaticAuthCallbacks.c.o)
  "_globalMemFree", referenced from:
      _freeCallbacksProvider in libcproducer.a(CallbacksProvider.c.o)
      _freeDeviceInfo in libcproducer.a(DeviceInfoProvider.c.o)
      _freeStreamInfoProvider in libcproducer.a(StreamInfoProvider.c.o)
      _freeStreamCallbacks in libcproducer.a(StreamCallbacksProvider.c.o)
      _freeContinuousRetryStreamCallbacks in libcproducer.a(ContinuousRetryStreamCallbacks.c.o)
      _freeStreamMapping in libcproducer.a(ContinuousRetryStreamCallbacks.c.o)
      _getStreamMapping in libcproducer.a(ContinuousRetryStreamCallbacks.c.o)`

**Comment by hassanctech** [comment]
I tried it really quick and I see the symbol is referenced by not defined in `libcproducer.a` as well as it is not defined in `libkvsCommonCurl.a` but it is referenced there:

$ nm -gC libcproducer.a | grep _curl_easy_strerror
no symbols
                 U _curl_easy_strerror
$ nm -gC libkvsCommonCurl.a | grep _curl_easy_strerror
                 U _curl_easy_strerror

It is expecting to link curl at runtime with a dynamic library.  That is how it is set up today, the static build doesn't bundle libcurl into the archive. 

If you want to make sure the other project uses the same libcurl you can make sure to specify it builds against the same one used for building cproducer.
