### ISSUE TITLE
[BUG]Function createKinesisVideoStreamSync execution takes too long 

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-producer-c#260]
Function **createKinesisVideoStreamSync** execution takes too long，the video uploaded by the device is incomplete。
the device start to upload video by calling func createKinesisVideoStreamSync at 14:36:35.758,  and this func return succcess at 14:36:43.584, it cost nearly 8s , please confirm!

Heres debug log：
	 [Mon Nov 15 14:36:35.758 2021] [14:36:26.769 info AWS_Record 767 Aws_record.c:186]Get KVS Stream ok
	 [Mon Nov 15 14:36:36.008 2021] 2021-11-15 06:36:26 WARN    onFrameDroppedFunc(): Frame with timestamp -1941871510 is dropped!
	 [Mon Nov 15 14:36:36.054 2021] 2021-11-15 06:36:27 WARN    onFrameDroppedFunc(): Frame with timestamp -1941871030 is dropped!
	 [Mon Nov 15 14:36:36.101 2021] 2021-11-15 06:36:27 WARN    onFrameDroppedFunc(): Frame with timestamp -1941870550 is dropped!
	 [Mon Nov 15 14:36:36.117 2021] 2021-11-15 06:36:27 WARN    onFrameDroppedFunc(): Frame with timestamp -1941868310 is dropped!
	 [Mon Nov 15 14:36:36.867 2021] 2021-11-15 06:36:28 WARN    describeStreamResult(): Retention period returned from the DescribeStream call doesn't match the one specified in the StreamInfo
	 [Mon Nov 15 14:36:36.882 2021] 2021-11-15 06:36:28 WARN    describeStreamResult(): Content type returned from the DescribeStream call doesn't match the one specified in the StreamInfo
	 [Mon Nov 15 14:36:36.882 2021] 2021-11-15 06:36:28 WARN    onFrameDroppedFunc(): Frame with timestamp -1941862070 is dropped!
	 [Mon Nov 15 14:36:37.304 2021] 2021-11-15 06:36:28 WARN    onFrameDroppedFunc(): Frame with timestamp -1941860150 is dropped!
	 [Mon Nov 15 14:36:37.945 2021] 2021-11-15 06:36:28 WARN    onFrameDroppedFunc(): Frame with timestamp -1941858390 is dropped!
	 [Mon Nov 15 14:36:38.554 2021] 2021-11-15 06:36:29 WARN    onFrameDroppedFunc(): Frame with timestamp -1941856150 is dropped!
	 [Mon Nov 15 14:36:38.913 2021] 2021-11-15 06:36:29 WARN    onFrameDroppedFunc(): Frame with timestamp -1941855510 is dropped!
	 [Mon Nov 15 14:36:39.054 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941852950 is dropped!
	 [Mon Nov 15 14:36:39.069 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941852470 is dropped!
	 [Mon Nov 15 14:36:39.069 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941850070 is dropped!
	 [Mon Nov 15 14:36:39.085 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941848630 is dropped!
	 [Mon Nov 15 14:36:39.085 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941847990 is dropped!
	 [Mon Nov 15 14:36:39.101 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941846230 is dropped!
	 [Mon Nov 15 14:36:39.101 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941845110 is dropped!
	 [Mon Nov 15 14:36:39.116 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941844790 is dropped!
	 [Mon Nov 15 14:36:39.148 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941843990 is dropped!
	 [Mon Nov 15 14:36:39.429 2021] 2021-11-15 06:36:30 WARN    onFrameDroppedFunc(): Frame with timestamp -1941841430 is dropped!
	 [Mon Nov 15 14:36:40.881 2021] [33] [36] [25] [33] [41] [33] [36] [25] [32] 2021-11-15 06:36:31 WARN    onFrameDroppedFunc(): Frame with timestamp -1941836950 is dropped!
	 [Mon Nov 15 14:36:41.428 2021] 2021-11-15 06:36:31 WARN    onFrameDroppedFunc(): Frame with timestamp -1941835030 is dropped!
	 [Mon Nov 15 14:36:41.694 2021] 2021-11-15 06:36:32 WARN    onFrameDroppedFunc(): Frame with timestamp -1941833910 is dropped!
	 [Mon Nov 15 14:36:41.944 2021] 2021-11-15 06:36:32 WARN    onFrameDroppedFunc(): Frame with timestamp -1941832470 is dropped!
	 [Mon Nov 15 14:36:41.991 2021] 2021-11-15 06:36:33 WARN    curlCompleteSync(): curl perform failed for url https://kinesisvideo.ap-east-1.amazonaws.com/getDataEndpoint with result Timeout was reached: Resolving timed out after 5000 milliseconds
	 [Mon Nov 15 14:36:42.022 2021] 2021-11-15 06:36:33 WARN    curlCompleteSync(): HTTP Error 0 : Response: (null)
	 [Mon Nov 15 14:36:42.287 2021] [14:36:33.147 warn AWS_Record 781 Aws_record.c:162]pktList size[501] reaches to threshold. Drop the list.
	 [Mon Nov 15 14:36:42.303 2021] [14:36:33.471 warn AWS_Record 781 Aws_record.c:133]hold size[248]. Drop the half list.
	 [Mon Nov 15 14:36:42.350 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941832150 is dropped!
	 [Mon Nov 15 14:36:42.491 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941830230 is dropped!
	 [Mon Nov 15 14:36:42.491 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941829750 is dropped!
	 [Mon Nov 15 14:36:42.506 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941826710 is dropped!
	 [Mon Nov 15 14:36:42.506 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941825590 is dropped!
	 [Mon Nov 15 14:36:42.522 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941824790 is dropped!
	 [Mon Nov 15 14:36:42.537 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941817430 is dropped!
	 [Mon Nov 15 14:36:42.537 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941817110 is dropped!
	 [Mon Nov 15 14:36:42.959 2021] 2021-11-15 06:36:33 WARN    onFrameDroppedFunc(): Frame with timestamp -1941814550 is dropped!
	 [Mon Nov 15 14:36:43.287 2021] 2021-11-15 06:36:34 WARN    onFrameDroppedFunc(): Frame with timestamp -1941813910 is dropped!
	 [Mon Nov 15 14:36:43.584 2021] [14:36:34.486 info AWS_Record 767 Aws_record.c:264]createKinesisVideoStreamSync streamHandle is [13529624]

**Comment by hassanctech** [comment]
I see this:

```
[Mon Nov 15 14:36:41.991 2021] 2021-11-15 06:36:33 WARN curlCompleteSync(): curl perform failed for url https://kinesisvideo.ap-east-1.amazonaws.com/getDataEndpoint with result Timeout was reached: Resolving timed out after 5000 milliseconds
```

It appears you're having issues with your network because this call timed out.  Do you start calling the putFrame APIs before create sync returns because it looks like you're getting the onFrameDroppedFunc() callbacks even before the create sync returned.  What is your buffer size set to perhaps you need to increase that as well.  Can you please provide VERBOSE logs from the SDK from the start of the `createKinesisVideoStreamSync` call?  If you could please attach them as a file here instead of pasting them in the comments that would be great.

Also, can you please share which commit you're using and any modifications you've made to the codebase.

Also it looks like there are some inconsistencies in your set up, see:

```
[Mon Nov 15 14:36:36.867 2021] 2021-11-15 06:36:28 WARN describeStreamResult(): Retention period returned from the DescribeStream call doesn't match the one specified in the StreamInfo
[Mon Nov 15 14:36:36.882 2021] 2021-11-15 06:36:28 WARN describeStreamResult(): Content type returned from the DescribeStream call doesn't match the one specified in the StreamInfo
```

Please resolve these as well make sure the retention period specified is consistent and same with the content type.

**Comment by disa6302** [comment]
Closing due to no response.
