### ISSUE TITLE
[QUESTION] hitting "continuousRetryStreamErrorReportHandler" error

### ISSUE THREAD

**Issue by pwijeratne** [awslabs/amazon-kinesis-video-streams-producer-c#263]
Opening a Stream to KVS and putting frames occasionally hit "continuousRetryStreamErrorReportHandler" and keeps looping

Using Kinesis producer-c v1.2.0

Following is a brief log output. See full log attached. I can see the stream is opened successfully and a "Stream Ready" callback was hit. Then at that point I am calling putKinesisVideoFrames and that function is not returning any errors. However I get continuousRetryStreamErrorReportHandler callback over and over. There is a `signAwsRequestInfo(): operation returned status code: 0x00000002` at time stamp 11:01:53:093.

What causes this error? What can I do to handle it properly? Thank you.
```
Nov 23 11:01:53.040 iCamera: [cp_pre_rec_buff.c:496:cp_alarm_start][CP] alarm_start
Nov 23 11:01:53.042 iCamera: [cp_alarm_state.c:224:alarm_state_machine_update][CP] State changed from Start to Continue
Nov 23 11:01:53.061 iCamera: [kvs_module.c:616:kvs_module_start][K
[continuousRetryStreamErrorReportHandler_error.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/7622680/continuousRetryStreamErrorReportHandler_error.log)
[continuousRetryStreamErrorReportHandler_error.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/7622681/continuousRetryStreamErrorReportHandler_error.log)
VS] Starting create Video Stream
Nov 23 11:01:53.061 iCamera: [kvs_module.c:622:kvs_module_start][KVS] 16158768, 0xffd3b8 0
Nov 23 11:01:53.061 iCamera: [kvs_module.c:215:defaultStreamReadyCallback]Stream Ready. Stream Handle: 16185656
Nov 23 11:01:53.061 iCamera: [kvs_module.c:629:kvs_module_start][KVS] Video Stream create time taken: [541]us
Nov 23 11:01:53.061 iCamera: [kvs_module.c:631:kvs_module_start][KVS] Video Stream created
Nov 23 11:01:53.061 iCamera: [fm_func.c:422:full_motion_start_handler]full_motion_start_handler triggered
Nov 23 11:01:53.061 iCamera: [aicdt.c:1827:aicdt_set_stream_name]Setting stream name c761f15d5e155c07a6598ee93df40a6feae21315dad18ec6e9cfaceacde36a80
Nov 23 11:01:53.088 iCamera: notifyDataAvailable(): Failed to un-pause curl with error: 43. Curl object 0xe36940
Nov 23 11:01:53.093 iCamera: [aicdt.c:1514:aicdt_savefile_thread]generate a new thumbnail: /tmp/ai/image/00_1637694113093.jpg
Nov 23 11:01:53.093 iCamera: signAwsRequestInfo(): operation returned status code: 0x00000002
Nov 23 11:01:53.093 iCamera: putStreamCurlHandler(): Stream with streamHandle 16185656 uploadHandle 16 has exited without triggering end-of-stream. Service call result: 0
Nov 23 11:01:53.099 iCamera: [alarm_handler.c:484:alarm_process_thumbnail]alarm_process_thumbnail waiting until the alarm_info has been populated
Nov 23 11:01:53.138 iCamera: [kvs_module.c:215:defaultStreamReadyCallback]Stream Ready. Stream Handle: 16185656
Nov 23 11:01:53.150 iCamera: notifyDataAvailable(): Failed to un-pause curl with error: 43. Curl object 0xed4568
Nov 23 11:01:53.150 iCamera: continuousRetryStreamErrorReportHandler(): Reporting stream error. Errored timecode: 0 Status: 0x00000002
Nov 23 11:01:53.150 iCamera: [kvs_module.c:296:defaultStreamErrorReportCallback][count:13]Reported streamError callback for stream handle 16185656. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x00000002
Nov 23 11:01:53.150 iCamera: signAwsRequestInfo(): operation returned status code: 0x00000002
Nov 23 11:01:53.150 iCamera: putStreamCurlHandler(): Stream with streamHandle 16185656 uploadHandle 17 has exited without triggering end-of-stream. Service call result: 0
Nov 23 11:01:53.150 iCamera: [kvs_module.c:215:defaultStreamReadyCallback]Stream Ready. Stream Handle: 16185656
Nov 23 11:01:53.160 iCamera: notifyDataAvailable(): Failed to un-pause curl with error: 43. Curl object 0xe36940
Nov 23 11:01:53.160 iCamera: continuousRetryStreamErrorReportHandler(): Reporting stream error. Errored timecode: 0 Status: 0x00000002
Nov 23 11:01:53.161 iCamera: signAwsRequestInfo(): operation returned status code: 0x00000002
```

**Comment by pwijeratne** [comment]
[continuousRetryStreamErrorReportHandler_error.log](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/7622687/continuousRetryStreamErrorReportHandler_error.log)

**Comment by disa6302** [comment]
@pwijeratne ,

I am still investigating to see what could be going on. From the logs, I see frequent curl call timeouts, that results in SERVICE_CALL_RESULT 599 to be returned and stream is recreated. When error 0x00000002 is encountered, I see the SERVICE_CALL_RESULT is not set, and we see these errors. Can you include a few more details on your application changes for your usecase?

**Comment by pwijeratne** [comment]
Our application has not changed. Our hardware changed to a faster processor, not sure if that has anything to do with the issue. May be the issue was there and we are starting to hit it now more due to the changed hardware.

**Comment by disa6302** [comment]
@pwijeratne , 

There are multiple code paths that throw this error unfortunately in `signAwsRequestInfo`, which makes it difficult to root cause. What I am trying to understand mostly is the code flow. What are the changes between the sample provided and your application? Trying to gather as many details to make it easier to understand what could be causing this.

**Comment by pwijeratne** [comment]
@disa6302, I set the log level as you suggested. Is there anything I can check to see if it got set properly? We have our application automatically run at start up, so I want to make sure the log level got set properly.

Regarding reproducibility of this issue: It only happens after about 3 days of running the application. When it happens, the application does not recover, so this is a critical issue we need to fix. Thank you.

**Comment by disa6302** [comment]
You should see log tags in the logs such as `VERBOSE` and `DEBUG`. With your previous log level, the log file contained only `WARN` and `ERROR`.

**Comment by disa6302** [comment]
Closing due to no response. Feel free to reopen if you have more information.
