### ISSUE TITLE
How to use producer timestamp？

### ISSUE THREAD

**Issue by Kelephant** [awslabs/amazon-kinesis-video-streams-producer-c#269]
My video stream will have its own time stamp. I want to use the producer's time stamp instead of the server's time stamp. Do I set "streaminfo. Streamcaps. Frametimecodes" to false?

**Comment by disa6302** [comment]
Hello @Kelephant ,

You can set your timestamp here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/6a7aab4fcde0791b5b092a15e61a5cacfc57c259/samples/KvsVideoOnlyStreamingSample.c#L153
presentationTimestamp is nothing but producer timestamp. 

Closing the issue assuming question is answered. Feel free to reopen if you have any more questions.
