### ISSUE TITLE
[BUG] Error while compiling on Big Sur on Mac Book Air 

### ISSUE THREAD

**Issue by mdhruv1** [awslabs/amazon-kinesis-video-streams-producer-c#271]
**Media pipeline:**
 - What is the media source (GStreamer, custom, etc). What is the upstream encoder/pipeline?
 - What is the media type, configuration
 - For Video - what's the codec information (Annex-B, AvCC, raw frames), CPD present, etc..
 - For Audio - what's the audio configuration (CPD generated, etc)..
 - Intermittent/continuous streaming?
Was  not able to compile

**Logging**
Add relevant SDK logging.  IMPORTANT NOTE:  Please make sure to NOT share AWS access credentials under any circumstance!  Please make sure they are not in the logs.

**Describe the bug**
trying to compile the code in a mac os m1 big sur
cmake .. -DBUILD_DEPENDENCY=TRUE

_ASN1_UTCTIME_cmp_time_t , _asn1_time_to_tm , _X509_VERIFY_PARAM_get_time , _err_clear_last_constant_time )
  "_vfprintf", referenced from:
      _OPENSSL_showfatal in cryptlib.o
  "_write$UNIX2003", referenced from:
      _conn_write in bss_conn.o
      _conn_puts in bss_conn.o
      _dgram_write in bss_dgram.o
      _fd_write in bss_fd.o
      _sock_write in bss_sock.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libcrypto.dylib] Error 1
make[3]: *** [all] Error 2
make[2]: *** [build/src/project_libopenssl-stamp/project_libopenssl-build] Error 2
make[1]: *** [CMakeFiles/project_libopenssl.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:93 (message):
  CMake step for libopenssl failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:69 (build_dependency)

**SDK version number**
Include the SDK version you are running. If it is a specific commit on master branch, include that

**Open source building**
If it is a build issue, include 3rd party library version and steps to how you are building it

**To Reproduce**
1 git clone 
2 mkdir build
3 goto the build directory
4 cmake .. -DBUILD_DEPENDENCY=TRUE

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
**Additional context**

**Comment by niyatim23** [comment]
Hi, this does not appear to be a KVS issue. You can try the following:

1. Since your machine seems to be 32-bit, you may need to set some flags while running cmake. Try `cmake .. -DBUILD_DEPENDENCY=TRUE -DBUILD_OPENSSL_PLATFORM=darwin-i386-cc` (platform codes are available [here](https://wiki.openssl.org/index.php/Compilation_and_Installation#OS_X) in case this is not the correct one for your case)
2. If the above step does not work, try to build the project dependencies standalone on your machine to isolate your issue

**Comment by disa6302** [comment]
Closing due to no response.
