### ISSUE TITLE
[QUESTION] What is the device storage size and for what is it used?

### ISSUE THREAD

**Issue by roxlu** [awslabs/amazon-kinesis-video-streams-producer-c#279]
The [documentation](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-c-write.html) talks about the device storage size and you can use `setDeviceInfoStorageSize()`.  Where and how is this used?

**Comment by MushMal** [comment]
This is the max storage in bytes to be used by the client. This is the storage for the frame data for buffering.

**Comment by roxlu** [comment]
Like you set this is related to #278.

Can you maybe explain what the purpose of this is? Is the storage size is that RAM or disk storage?

**Comment by MushMal** [comment]
The default storage is implemented in RAM so in that sense, yes, it will be the size of the RAM that will be reserved and used for storage for all of your streams buffering needs.
