### ISSUE TITLE
How about remove websocket stuff in producer C sdk?

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#28]
Hi,

As producer C sdk is not use websocket. Can I remove websocket stuff from master branch?
Do you have any plan to use websocket in the further?

Best regards,
Aaron

**Comment by awsa2ron** [comment]
Looks, webrtc sdk reuse this producer c sdk. Does webrtc sdk need websocket? and need to compile websocket here in producer sdk?

**Comment by MushMal** [comment]
@awsa2ron not sure I understand the question. Perhaps you refer to libWebSockets library?

Producer C has a Common library that's used by the producer codebase and by the webRTC codebase. This is used to make calls to HTTPS protocols. Primarily, this is used in WebRTC context for the IoT credentials.

By default, when you compile the C producer, libCurl is used. When you compile the WebRTC, libWebSockets is used (we also use libWebSockets directly in the signaling client in WebRTC).

Please let me know if this helps.

**Comment by awsa2ron** [comment]
Yes, thank you for good explanation.
I just wonder could I remove libwebsocket in producer C sdk, because producer C sdk no need websocket. Remove it may help to simplify.

**Comment by MushMal** [comment]
Ideally, we should move the Common to a project of its own. We use libWebSockets implementation of IoT credential provider (https) for webRTC solely for the purpose of not duplicating the networking client stacks to keep the footprint to minimum.

The footprint is still the minimal considering that it's a compile time option to select curl or libWebSockets for Common.

I am going to resolve this issue for now. Please feel free to reopen if you need more context.
