### ISSUE TITLE
[FEATURE]H.265 support

### ISSUE THREAD

**Issue by d0oo0b** [awslabs/amazon-kinesis-video-streams-producer-c#283]
**Is your feature request related to a problem? Please describe.**
I can not create a video stream with codec of H.265.

**Describe the solution you'd like**
H.265 can be support in the producer-c.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by d0oo0b** [comment]
Hi,

Thanks for your reply.
Could you please confirm for me that the function “createRealtimeAudioVideoStreamInfoProviderWithCodecs” is work in the least  release(1.2.0)?
I can not find this function in amazon-kinesis-video-streams-producer-c/src/include/com/amazonaws/kinesis/video/cproducer/Include.h of 1.2.0.

**Comment by hassanctech** [comment]
These were added after the 1.2.0 release.  We have a planned release of 1.3.0 coming up in the near term if you'd like you can wait for that.  For now you can try: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/commit/6d9d47c064f35fbe4443b4d0420c67410d1c465b (which is the current release candidate -- but NOT the official release).

**Comment by zhangzhao-a11y** [comment]
I build prompt me this error
![image](https://user-images.githubusercontent.com/83795698/155284322-c3ffad71-03d5-45eb-990e-8df632e1774a.png)

**Comment by hassanctech** [comment]
I think perhaps you did not do a clean build you have to delete all the dependencies.  Those things you are missing are defined in PIC in this commit:  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/04fdbdffa929f7390b946493ce8a995fb09c0ceb/src/client/include/com/amazonaws/kinesis/video/client/Include.h

If you did not update your PIC (the C Producer commit hash I referenced above already references the newer PIC) then you will hit this issue.  If you wipe out all the open source and dependency and build folders in your build then do a clean build after that you should have no issue.

**Comment by zhangzhao-a11y** [comment]
![image](https://user-images.githubusercontent.com/83795698/155907988-eb6d1fb9-f13a-4bb9-9b8c-601a48076b9d.png)
I got an error like this，I use  "-muclibc" this parameter

**Comment by yy-arya** [comment]
When using H265, are there any requirements for the corresponding audio format?  AAC or G711？I want to know if H265+g711 is supported？

**Comment by daveisfera** [comment]
KVS can receive both [AAC and PCM as audio inputs](https://aws.amazon.com/kinesis/video-streams/faqs/), but [HLS only supports AAC](https://en.wikipedia.org/wiki/HTTP_Live_Streaming#Architecture)

**Comment by disa6302** [comment]
@d0oo0b , 

HLS supports only AAC. This link has some details. 
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/hls-playback.html

Closing this issue. Feel free to reach out if you have more questions.

**Comment by d0oo0b** [comment]
>>Viewer gets UnsupportedStreamMediaTypeException after calling AmazonKinesisVideoArchivedMediaClient.GetDASHStreamingSessionURLAsync.

This is the case for DASH, not HLS. @disa6302 @daveisfera

**Comment by disa6302** [comment]
Please follow the link attached. There is a statement that says only AAC is supported. 

"The audio track (if present) of each fragment **must** contain codec private data in the AAC format"

**Comment by disa6302** [comment]
The question is about DASH and not HLS. @d0oo0b , let me get back to you. We do support G.711 for DASH according to the docs: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetDASHStreamingSessionURL.html.

**Comment by disa6302** [comment]
@d0oo0b , 

2 points:
1. The API GetDashStreamingSessionURL allows AAC and G.711 (alaw and mulaw). 
2. G.711 would not work if using the browser for HLS/DASH playback.

Can you include details on how you are consuming the media on the viewer end? It is possible the first fragment is being dropped or does not contain the codec details? Do you see any errors on the producer end?

**Comment by yy-arya** [comment]
@disa6302 @daveisfera 
Hi, we use DASH to play it. This is the viewer appears error when it get the media. I guess the codec is right， so we don't know why it returns unsupported. 
```
{"response_id":"da9166d5b8314ea0a12ffe40ea368475","timestamp":1646287027638,"code":"1000","message":"One or more errors occurred. (The type of the media is not supported or could not be determined from the media codec ids: (track 1: V_MPEGH/ISO/HEVC), (track 2: A_MS/ACM).)","data":{}} 
```

**Comment by d0oo0b** [comment]
> 

hi @disa6302, 
1. The details on how we are consuming the media on the viewer, you can find the code as below, highlighted with red border:
![Image from iOS (3)](https://user-images.githubusercontent.com/8717950/159613597-1f525dc7-3470-4177-9b88-5b29620095a0.png)
And we got returns as below:
`{"response_id":"da9166d5b8314ea0a12ffe40ea368475","timestamp":1646287027638,"code":"1000","message":"One or more errors occurred. (The type of the media is not supported or could not be determined from the media codec ids: (track 1: V_MPEGH/ISO/HEVC), (track 2: A_MS/ACM).)","data":{}} `

2. There is no error on the producer, we send DASH as same as HLS, the code as below 
![g711-1](https://user-images.githubusercontent.com/8717950/159614690-1117e257-34cc-4be7-af4e-d90a33080dfc.jpeg)

 It is working well when we send DASH and HLS with H.264 codec, we check it many time and confirmed there are no mistake in the up streaming.

**Comment by yy-arya** [comment]
@disa6302 
Hi， It is support H.264/265 + AAC works But not H.264/265 + G.711.

**Comment by jdelapla** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/333
