### ISSUE TITLE
[QUESTION] Why the kvs console can not playback the video in alaw

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-producer-c#286]
After switching the audio codec from aac to alaw, the console can not play the video. However, when I choose to download clip, it can succeeded.

![image](https://user-images.githubusercontent.com/20633988/155477736-23ad1bd5-9479-46dd-9bd6-9738549efa24.png)

**Comment by niyatim23** [comment]
Hi @Nomidia, browsers do not support any sort of PCM based audio via HLS/DASH. AAC is the only codec support by both KVS and browsers. 

Closing assuming answered, feel free to reopen the issue in case of any further questions.
