### ISSUE TITLE
[FEATURE] Tag for 1.3.0 release candidate

### ISSUE THREAD

**Issue by daveisfera** [awslabs/amazon-kinesis-video-streams-producer-c#292]
**Is your feature request related to a problem? Please describe.**
Ability to checkout 1.3.0 release candidate without the entire repo

**Describe the solution you'd like**
Create tag for the 1.3.0 release candidate ( mentioned as a potential solution [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/283#issuecomment-1061048930) )

**Describe alternatives you've considered**
The entire repo can be cloned and then a specific commit checked out, but being able to clone just a tag is more efficient and nice that it can be done with a single command

**Comment by disa6302** [comment]
Not sure what you mean but we do tag releases everytime. We are working on tagging a release 1.3.0, will update the thread when we have a new release out

**Comment by daveisfera** [comment]
I mean to create a tag from the current `master` branch called `v1.3.0-rc0` or `v1.3.0-beta0` so that it's recorded in `git` and can be easily checked out just that code rather than having to clone the whole repo

**Comment by daveisfera** [comment]
Here's info about how the [naming works as part of standard versioning practices with examples](https://semver.org/#spec-item-11)

**Comment by disa6302** [comment]
Release 1.3.0 available now: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/releases/tag/v1.3.0
Closing.
