### ISSUE TITLE
[QUESTION]createDefaultCallbacksProviderWithIotCertificate failed

### ISSUE THREAD

**Issue by yy-arya** [awslabs/amazon-kinesis-video-streams-producer-c#296]
I get a error 0x15000025 when init kvs producer createDefaultCallbacksProviderWithIotCertificate().

I found the explain is STATUS_STREAM_BEING_SHUTDOWN， But I can't understand the specific reason of the error, is the certificate verification failed?

**Comment by disa6302** [comment]
There seems to be an overlap of error code definition. However, in the context of `createDefaultCallbacksProviderWithIotCertificate()`, it indicates that the [curl call failed](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/79da5b6d6ad67560cc08530f967e9187a6d1c594/src/include/com/amazonaws/kinesis/video/common/Include.h#L53). Check network connection. Check the log to understand what the curl call error result is. 
The logs should contain lines such as "Curl perform failed for url..." and/or "Curl call response failed with http status.."
This will give clarity on what could be going on.
