### ISSUE TITLE
[QUESTION] What are the parameters of the aac sample audio used in the sample application?

### ISSUE THREAD

**Issue by pourna18** [awslabs/amazon-kinesis-video-streams-producer-c#297]
I would like to know what are the parameters for the aac audio used in the sample application. I tried with my own aac adts encoded audio but the amazon console is not able to decode the audio. I would like to know the parameters of the audio to recreate with my own, also are there any changes to be made in the sample application to support adts aac?

**Comment by disa6302** [comment]
@pourna18 , 

We do not support ADTS header currently. Check this: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/51

We allow do a NAL or AVCC adaptation.
