### ISSUE TITLE
[QUESTION] - EOS, End of Stream

### ISSUE THREAD

**Issue by diegocatalao** [awslabs/amazon-kinesis-video-streams-producer-c#302]
Good afternoon folks.

Thank you for your patience in answering the questions and for the excellent work on the lib.
I would like to know if there is any flag inside the `putKinesisVideoFrame` that tells me if the stream ended. I would like to replace this in the Main Loop.

**Comment by diegocatalao** [comment]
@MushMal  Actually I would like to know if all the packages I sent have finished sending successfully. Today I can tell if the video was completely streamed by while: `while (defaultGetTime() < streamStopTime)`. I would like to know if all files were uploaded successfully.

**Comment by MushMal** [comment]
I am unfamiliar with kinesisVideoStreamDefaultEndOfStream. If you are developing your own application based on the C producer SDK, you could call the sync version of the stopStream which will either err out with a timeout in case of an error or would return as soon as it finishes streaming the last bit of the stream and receives the persisted ACK. Alternatively, for more control, you could handle fragment ACKs in the fragment ack callback https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1643

Here is more information about the ACKs https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/structures.md#fragment-acks

**Comment by diegocatalao** [comment]
With this I can check if my pipeline is empty?

**Comment by diegocatalao** [comment]
I can tell if my pipeline is empty from this?

**Comment by diegocatalao** [comment]
Thank you for your attention, @MushMal .
I actually managed to upload the entire video and wait for the threads to finish before continuing to run.

Thank you very much,
I hope to soon contribute new resources to this project.

Best Regards
