### ISSUE TITLE
[QUESTION] How to set start timestamp?

### ISSUE THREAD

**Issue by daveisfera** [awslabs/amazon-kinesis-video-streams-producer-c#303]
Is it possible to set [`ProducerStartTimestamp`](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html#API_dataplane_PutMedia_RequestSyntax) when using relative timestamps? I've look through the documentation and code, but haven't see a way to do it? Is there something I've missed that allows it to happen?

**Comment by MushMal** [comment]
Here is a documentation I put together a while back for the timestamps: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docs/timestamps.md

There are some implications when using the relative timestamps - for example, mapping the timestamps on the consumer side as the backend always uses absolute timestamps. The SDK itself maps back the ACK timestamps correctly though.

The absolute/relative TS can be specified here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1000

**Comment by daveisfera** [comment]
Yes, I read that document, but I don't see any way to specify the start timestamp when using relative mode. It appears to be using the current time and that works for video that's being uploaded in realtime, but I'm currently uploading a video that was recorded in the past and would like the timestamp to match when it was actually recorded and I have that working with absolute timestamps, but I was just curious if it was possible to have it work with relative timestamps as well to simplify things.

**Comment by MushMal** [comment]
Oh I see. It seems there is not an easy programmatic way to do that. Here is the relevant code:

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/CurlApiCallbacks.c#L2048-L2050

Alternatively, most cases, the frame timestamps can be adjusted on-the-fly and absolute timestamps are used. This is how gstreamer plugin operates in some modes.

**Comment by daveisfera** [comment]
Yes, I'm looking for a way to specify `startTimestamp` that is passed to that function. Sounds like there's not a way to specify that. Feel free to turn this into a feature request and/or close it out.

**Comment by diegocatalao** [comment]
@daveisfera You can look at this issue I opened a while ago. I hope it helps. Don't forget to change your stream to Offline.

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/301

**Comment by daveisfera** [comment]
Thanks for the heads up. What do you mean by "change your stream to Offline"? Is that something to do in the Producer SDK?

**Comment by diegocatalao** [comment]
Exactly. At the time of initializing the stream provider:

`    CHK_STATUS(createOfflineVideoStreamInfoProvider(
        stream_name, retention_period, buffer_duration, &pStreamInfo
    ));
`

**Comment by daveisfera** [comment]
Oh, I didn't realize that function exists, but using it allowed me to remove the short sleep I had to put in to make the file upload not fail, so that's great.

**Comment by disa6302** [comment]
Resolving since the question is answered. Feel free to reach out if you have more questions.
