### ISSUE TITLE
[BUG] Hang when connection times out with 599

### ISSUE THREAD

**Issue by daveisfera** [awslabs/amazon-kinesis-video-streams-producer-c#309]
**Media pipeline:**
 - What is the media source (GStreamer, custom, etc). What is the upstream encoder/pipeline? custom
 - What is the media type, configuration: Video (both with and without video)
 - For Video - what's the codec information (Annex-B, AvCC, raw frames), CPD present, etc..: H.264 and H.265
 - For Audio - what's the audio configuration (CPD generated, etc)..: No audio, AAC and PCM
 - Intermittent/continuous streaming? Both

**Logging**
```
curlCompleteSync(): curl perform failed for url https://s-d022f287.kinesisvideo.us-east-1.amazonaws.com/putMedia with result Timeout was reached: Operation too slow. Less than 30 bytes/sec transferred the last 30 seconds
curlCompleteSync(): HTTP Error 0 : Response: (null)
Request URL: https://s-d022f287.kinesisvideo.us-east-1.amazonaws.com/putMedia
Request Headers:
    Authorization: AWS4-HMAC-SHA256 Credential=..., SignedHeaders=connection;host;transfer-encoding;user-agent;x-amz-date;x-amzn-fragment-acknowledgment-required;x-amzn-fragment-timecode-type;x-amzn-producer-start-timestamp;x-amzn-stream-name, Signature=...
    connection: keep-alive
    content-type: application/json
    host: s-d022f287.kinesisvideo.us-east-1.amazonaws.com
    transfer-encoding: chunked
    user-agent: AWS-SDK-KVS/3.0.0 GCC/10.2.1 Linux/5.10.104-linuxkit x86_64
    X-Amz-Date: 20220531T001628Z
    x-amzn-fragment-acknowledgment-required: 1
    x-amzn-fragment-timecode-type: ABSOLUTE
    x-amzn-producer-start-timestamp: 1653956188.599
    x-amzn-stream-name: dljtest
putStreamCurlHandler(): Stream with streamHandle 94238676060848 uploadHandle 0 has exited without triggering end-of-stream. Service call result: 599
kinesisVideoStreamTerminated(): Stream 0x55b5a6cf8ab0 terminated upload handle 0 with service call result 599.
```

**Describe the bug**
The Producer SDK will hang and stop sending data when a return status of 599 is encountered

**SDK version number**
1.3.0

**Open source building**
Built in a Docker container using Debian Bullseye

**To Reproduce**
Happens occasionally when uploading video

**Expected behavior**
Retry after the timeout or fail with an error

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser [e.g. chrome, safari]: N/A
 - Version [e.g. 22]: N/A

**Comment by jdelapla** [comment]
the curl has an http code of 0, and 599 indicating there was a connection time out. It appears network connectivity was lost.

**Comment by daveisfera** [comment]
Yes, but why does it slow down and then time out? That appears to be a bug in the SDK and it's data handling...
