### ISSUE TITLE
[BUG]stuck in func frameOrderCoordinatorPutFrame() while putting frame;

### ISSUE THREAD

**Issue by August88618** [awslabs/amazon-kinesis-video-streams-producer-c#310]
Question 1：When frame data is uploaded, it will occasionally get stuck in the function frameOrderCoordinatorPutFrame. The debugging trace shows that the stuck position is in the while loop, please confirm!
func:
	STATUS frameOrderCoordinatorPutFrame(PKinesisVideoStream pKinesisVideoStream, PFrame pUserFrame)
	{
		...
		DLOGE("before stackQueueEnqueue.");
		CHK_STATUS(stackQueueEnqueue(pPutFrameTrackData->frameQueue, (UINT64) pFrame));

		if (pPutFrameTrackData->frameCount == 0) {
			pFrameOrderCoordinator->trackWithFrame++;
		}
		pPutFrameTrackData->frameCount++;

		// only put earliest frame when all tracks have frame
		while (pFrameOrderCoordinator->trackWithFrame == pFrameOrderCoordinator->putFrameTrackDataListCount) {
			CHK_STATUS(putEarliestFrame(pKinesisVideoStream));
		}
		DLOGE("exit putEarliestFrame.");
	}
	
	

**SDK version number**
[amazon-kinesis-video-streams-producer-c]master:Update PIC with duplicate fix #295

Trace log：
[aws.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/8948845/aws.txt)

[amazonSdkLog.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/8948866/amazonSdkLog.txt)

**Comment by hassanctech** [comment]
@August88618 Can you please try with the latest release:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/releases/tag/v1.4.1 ?  In general we recommend using the latest release versions.

**Comment by hassanctech** [comment]
Closing due to no response.  @August88618 if you are still experiencing issues please re-open with details.  The issue should be resolved in the release mentioned above.
