### ISSUE TITLE
[QUESTION] streamConnectionStaleFn retry loop running with no backoff logic

### ISSUE THREAD

**Issue by mitchellhansen-wyze** [awslabs/amazon-kinesis-video-streams-producer-c#316]
Hello!

We have implemented a callback for the `streamConnectionStaleFn` callback based on the recommendation in this ticket : https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/242

> As mentioned, your application could simply reset the connection on the staleness. Unlike buffer pressures, the staleness connection is more tied up with the networking thread.

Specifically, we call `kinesisVideoStreamResetConnection(streamHandle);` when receiving a `streamConnectionStaleFn` trigger.

This works in most cases. But, in certain edge cases, this will put the library into a continuous retry loop that it does not like to recover from. You can see an instance of this behaviour in this log : https://gist.github.com/mitchellhansen-wyze/9c4c73ab18db3ac39bf480de40598fd7

You can see a much more egregious example of this hot-looping here : https://gist.github.com/mitchellhansen-wyze/135db274f99741bee3c382ca2be60f60

I see that there has been some work done to try and mitigate this problem via exponential backoff logic in the ContinuousRetry state machine : https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/247

It would be ideal if this logic could be upstreamed to the producer-c library itself, it seems like that PR could have been created to target this exact issue I'm seeing. 

But in the meantime, is it possible to add this backoff logic in my implementation of the `streamConnectionStaleFn`? Would blocking for 1, or 2, or even 10 seconds in this callback cause any issues in the state machine?

**Comment by disa6302** [comment]
@mitchellhansen-wyze , 

What version of the SDK are you using? 
Also, I am interested in knowing why you want to use the callback to reset the connection? The reason I ask is, with continuous retry, the SDK resets the connection by default. 
The code here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/79da5b6d6ad67560cc08530f967e9187a6d1c594/src/source/ContinuousRetryStreamCallbacks.c#L268 invokes `kinesisVideoStreamResetConnection` internally. Can you try running the SDK without your Stale state machine callback to see if you hit this issue? 

Meanwhile, I will look deeper into the code and the logs to understand what could be going on. More details on how your application is modelled would also be helpful. 

Also FYI: We do have exponential backoff logic being used in PIC in version 1.3.0 of producer C SDK.

**Comment by mitchellhansen-wyze** [comment]
Hello @disa6302 !

1.) SDK Version 1.2

2.) I'm actually not sure why we manually do the stream reset in the callback, I believe this was a mitigation either suggested by our AMZ contact, or something to do with an older version of the library. 

> Can you try running the SDK without your Stale state machine callback to see if you hit this issue?

Yep! I can try that out. And actually, I'm now wondering if I should be overriding *any* of the default handlers, we currently override the following :

```
        info->pStreamCallbacks->bufferDurationOverflowPressureFn = wyzeBufferDurationOverflowCallback;
        info->pStreamCallbacks->streamLatencyPressureFn = wyzeStreamLatencyPressureCallback;
        info->pStreamCallbacks->streamConnectionStaleFn = wyzeStreamConnectionStaleCallback;
        info->pStreamCallbacks->droppedFrameReportFn = wyzeDroppedFrameReportCallback;
        info->pStreamCallbacks->droppedFragmentReportFn = wyzeDroppedFragmentReportCallback;
        info->pStreamCallbacks->streamErrorReportFn = wyzeStreamErrorReportCallback;
        info->pStreamCallbacks->fragmentAckReceivedFn = wyzeFragmentAckReceivedCallback;
        info->pStreamCallbacks->streamReadyFn = wyzeStreamReadyCallback;
        info->pStreamCallbacks->streamClosedFn = wyzeStreamClosedCallback;
        info->pStreamCallbacks->streamShutdownFn = wyzeStreamShutdownCallback;
```

Some of these seem to just be for info, like `fragmentAckReceivedFn`, while others are critical for the functionality of the library, such as `streamConnectionStaleFn`. Should we avoid overriding any of these callbacks?

3.) In regards to 

```
UINT64 bufferDuration;
UINT64 replayDuration;
UINT64 connectionStalenessDuration;
```

We actually do not set these value, they are left to their defaults. Do you have any suggestions for values that we can set for these parameters?

4.) > Also FYI: We do have exponential backoff logic being used in PIC in version 1.3.0 of producer C SDK.

That is great to hear! We are currently in the process of upgrading to version 1.3. Hopefully that will also increase our stability

Thanks!

**Comment by disa6302** [comment]
The default implementations cover most of the action cases. Unless, you would like to do something other than what the SDK does in these callbacks, you can use the default implementations. Having said this, if you could attach your code snippet for your callback implementation, it would be helpful.

**Comment by MushMal** [comment]
You can cascade the callbacks. Check out addStreamCallbacks API at https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L425

You can see how it's used in the samples and in the continuous retry logic. 

Basically, you can use createStreamCallbacks API https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/412aab82c99a72f9dbde975f5fea81ffdc844ae5/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L755 to create the default structure. Add your handler for the specific callback function, then add the callback to the chain. There are other providers you can chain - for example, the auth provider, etc..

**Comment by mitchellhansen-wyze** [comment]
@MushMal This is actually what we are already doing : 

```
        // This calls createDefaultCallbacksProviderWithAwsCredentials internally
        CHK_STATUS(create_client_callbacks(config, &pClientCallbacks));

        CHK_STATUS(createStreamCallbacks(&(info->pStreamCallbacks)));
        info->pStreamCallbacks->customData = (UINT64)get_kvs_info();
        info->pStreamCallbacks->bufferDurationOverflowPressureFn = wyzeBufferDurationOverflowCallback;
        info->pStreamCallbacks->streamLatencyPressureFn = wyzeStreamLatencyPressureCallback;
        info->pStreamCallbacks->streamConnectionStaleFn = wyzeStreamConnectionStaleCallback;
        info->pStreamCallbacks->droppedFrameReportFn = wyzeDroppedFrameReportCallback;
        info->pStreamCallbacks->droppedFragmentReportFn = wyzeDroppedFragmentReportCallback;
        info->pStreamCallbacks->streamErrorReportFn = wyzeStreamErrorReportCallback;
        info->pStreamCallbacks->fragmentAckReceivedFn = wyzeFragmentAckReceivedCallback;
        info->pStreamCallbacks->streamReadyFn = wyzeStreamReadyCallback;
        info->pStreamCallbacks->streamClosedFn = wyzeStreamClosedCallback;
        info->pStreamCallbacks->streamShutdownFn = wyzeStreamShutdownCallback;
        info->pStreamCallbacks->freeStreamCallbacksFn = NULL;

        CHK_STATUS(addStreamCallbacks(pClientCallbacks, info->pStreamCallbacks));
```

Does this mean these callbacks are already chained? Or should we be doing something like this :

```
        // This calls createDefaultCallbacksProviderWithAwsCredentials internally
        CHK_STATUS(create_client_callbacks(config, &pClientCallbacks));

        CHK_STATUS(createStreamCallbacks(&(info->pStreamCallbacks)));
        CHK_STATUS(addStreamCallbacks(pClientCallbacks, info->pStreamCallbacks));

        info->pStreamCallbacks->customData = (UINT64)get_kvs_info();
        info->pStreamCallbacks->bufferDurationOverflowPressureFn = wyzeBufferDurationOverflowCallback;
        info->pStreamCallbacks->streamLatencyPressureFn = wyzeStreamLatencyPressureCallback;
        info->pStreamCallbacks->streamConnectionStaleFn = wyzeStreamConnectionStaleCallback;
        info->pStreamCallbacks->droppedFrameReportFn = wyzeDroppedFrameReportCallback;
        info->pStreamCallbacks->droppedFragmentReportFn = wyzeDroppedFragmentReportCallback;
        info->pStreamCallbacks->streamErrorReportFn = wyzeStreamErrorReportCallback;
        info->pStreamCallbacks->fragmentAckReceivedFn = wyzeFragmentAckReceivedCallback;
        info->pStreamCallbacks->streamReadyFn = wyzeStreamReadyCallback;
        info->pStreamCallbacks->streamClosedFn = wyzeStreamClosedCallback;
        info->pStreamCallbacks->streamShutdownFn = wyzeStreamShutdownCallback;
        info->pStreamCallbacks->freeStreamCallbacksFn = NULL;

        CHK_STATUS(addStreamCallbacks(pClientCallbacks, info->pStreamCallbacks));
```

**Comment by MushMal** [comment]
addStreamCallbacks does the chaining. I am not sure why you would add twice in your second example but the first one is the right one.

**Comment by MushMal** [comment]
Also, I haven't checked the latest code but returning an error from any of the callbacks will terminate the chain

**Comment by mitchellhansen-wyze** [comment]
@MushMal Got it, thank you. In that case it seems that our callbacks already chained. I will remove the stream reset logic from our chained ConnectionStaleCallback and see if that improves stability. 

Thanks!
