### ISSUE TITLE
[QUESTION] Any snippets or examples using c producer libs curl/sigv4/credentials functions to upload an image to s3?

### ISSUE THREAD

**Issue by mjdietzx** [awslabs/amazon-kinesis-video-streams-producer-c#319]
I am working on an IoT device that streams video to KVS (why we use c producer lib), as well as uploading images to s3. C Producer lib has been great, it is working very well. `createDefaultCallbacksProviderWithIotCertificate` is a really nice helper function that makes authenticating simple. My device has its IoT core certificates that have permissions attached to stream to KVS as well as upload photos to s3, and this "just works"

When it comes to uploading photos to s3 it has been such a pain. I can't find any good example of doing this with curl due to sigv4 signing trickiness and likely some s3 gotchas that I am getting caught up on. I would hate to bring in another big sdk like https://github.com/aws/aws-iot-device-sdk-embedded-C, especially when I am on embedded linux and have curl and this lib which seems to be more than enough to do what I need to do (upload an image to s3).

Looking through the functions in this lib, it seems it wouldn't be too hard to upload an image to s3. Can anyone help me out by providing a code snippet or some pseudo-code on how to do this? I would love to do it with the device cert/key, but I could also provide an access key/security token/session token.

Thanks!

**Comment by MushMal** [comment]
Apparently, uploading images (thumbnails for example) is quite a common thing. I would hope that the AWS folks would have some suggestions for this. While I am not very familiar with the SigV4 calculation for S3 puts, those should be pretty straightforward once you iron out the issues with the way the signature is calculated. For KVS, the signature calculation routine as well as the HTTP request furnishing is done in a targeted fashion in the C producer SDK - you might use large parts of IoT credential provider as well as the HTTP routines but you might need to do some adaptations.

Incidentally, architecturally, try to explore ways to do this in the backend via lambda or something. For example, if you have some backend processing on the incoming stream which also decodes the stream then you could just do S3 push of the images from the backend. Another approach would be to have a separate stream of images only which then on the backend can be stored in KVS and retrieved on demand. You could also push those images to S3 if needed. Sorry, not much help here I feel.

**Comment by mjdietzx** [comment]
Thanks for the response @MushMal . 

Uploading images is so common. It is a shame it is so complicated. I am yet to find a good way to upload an image to an s3 bucket while authenticated using `curl`. It is crazy to me..

ie you would think it would be straightforward to get something like: 
```bash
curl --tlsv1.2 --cert /path/to/device.crt --key /path/to/device.key -H "Content-Type: image/jpeg" -H "Date: $(date -R)" 'https://<bucket_name>s3.<region>.amazonaws.com/test.jpg' --upload-file test.jpg -vvv
```

or
```bash
curl --aws-sigv4 "aws:amz:us-east-1:s3" --user "<access_key>:<secret_token>" -H "X-Amz-Security-Token: <session_token>" -H "Content-Type: image/jpeg" -H "Date: $(date -R)" -H "x-amz-content-sha256: <payload_hash>" 'https://<bucket_name>s3.<region>.amazonaws.com/test.jpg' --upload-file test.jpg -vvv
```

I am yet to get this working and can't find anything good and simple or some standard aws doc on how to do this with curl. It is really easy if you have a presigned url to upload to, or if the s3 bucket allows public uploads. But once I try to do this in an authenticated manner it has been tricky

**Comment by hassanctech** [comment]
@mjdietzx Does this address your use case:  https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/images.html

We've added an on demand GetImages API and an automated image generation mode which will configure Kinesis Video Streams to automatically upload images to S3.

**Comment by mjdietzx** [comment]
Hey @hassanctech the link you shared looks very interesting/amazing. It does not exactly address my use-case. To provide a bit more info, our stream is very low-res/quality compare to the images we upload to s3 (very high res/quality). Stream quality is based on wifi signal strength/user's bandwidth and can be very low res/bitrate. While our jpgs are using full res and minimal compression, a single photo of ours can be 2MB.

That said, I was able to make a few very minor tweaks to c producer lib to a) get credentials via callback (I use c producer lib IoT auth with the device certs) b) use these credentials to presign a s3 put upload - using the c producer lib functions to do this c) put the image to that signed url with a generic `curl` request

I will make a PR because and see what you think. It is a few lines of code that just makes some of these helper functions in c producer lib more configurable.

I also think we will use https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/images.html, that looks like an amazing feature, it just may be used in addition to what we already do and in the future. Thank you for sharing that
