### ISSUE TITLE
”Fragment decoding error“ on Media playback, when change aac audio sample frequence to 16K 

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#32]
Aac audio config on our system is 16k sample frequency/16 bit, 2 channel .
So we change "KvsAacAudioVideoStreamingSample.c" aac cpd as below:
```
-    BYTE audioCpd[] = {0x11, 0x90, 0x56, 0xe5, 0x00};
+    //BYTE audioCpd[] = {0x11, 0x90, 0x56, 0xe5, 0x00};
+       BYTE audioCpd[] = {0x00,0x00, 0x56, 0xe5, 0x00};
+    UINT32 samplingFrequency = 16000;
+    UINT16 channelConfig = 1;
+    mkvgenGenerateAacCpd(AAC_LC, samplingFrequency, channelConfig, audioCpd, 2);
 
```
And change the source of aac audio from original 48K/2 channel to 16k/16 bit, 2 channel.
Then got this error:
```
There was an error decoding the media. Verify that the stream contains valid content.
Details
Codec ID:
avc1.64001e (H.264 High@3.0)
mp4a.40.2 (AAC LC)
Fragment number: 91343852333182220975342367885794392124477188063
Server timestamp: March 13, 2020 4:34:20 PM
Size: 911.2 KB
```

Player don't support this aac format?

Best regards,
Aaron

**Comment by awsa2ron** [comment]
BTW, we try to open HLS URL in safari and see the video. But still not hear audio.

**Comment by chehefen** [comment]
I verified that 16k 2 channel works using frames produced by gstreamer. Can you refer to this to modify the sample? https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/31/files#diff-23d0cc554d6cb2465d56f97e3eecbb76. Make sure you are also setting the pAudioTrack->codecPrivateDataSize correctly.

**Comment by awsa2ron** [comment]
Yes, our audio source is not raw data, but with ADTS headr, unlike the sample audio.
It works after remove the first 7 bytes of each of them.
