### ISSUE TITLE
[QUESTION] 0x52000060 error occurred and there was no video for several tens of seconds at the time of occurrence

### ISSUE THREAD

**Issue by Hanan-ob** [awslabs/amazon-kinesis-video-streams-producer-c#322]
Our device connects 2 or 3 IP cameras to create each KVS stream, sending audio and video data to the KVS every day.

**Action overview**
- The KVS stream operation was performed for more than a day by connecting two IP cameras.

**Problem phenomenon**
- It was found that an error of 0x52000060 occurred in one of the two streams.
- There is no video for several tens of seconds after checking (clip download) the saved video at the time the error occurred.
- Even in previous tests, 0x52000060 errors often occurred.
- The error occurs as follows.
    [2022-08-18 02:05:20 UTC+9] kvsStatus: 0x52000060
    [2022-08-18 02:05:22 UTC+9] kvsStatus: 0x52000060
    [2022-08-18 09:09:28 UTC+9] kvsStatus: 0x52000060

`08-18 02:05:20.349 E 18254    27196    KvsStream:                                                      [JNI] [DEV-STREAM-2] [H:1] [T:JNIKvsStream-dev1] kvsStreamErrorReportCallback Reported streamError callback for stream handle 510856029208. Upload handle 21. Fragment timecode in 100ns: 16607558880300000. Error status: 0x52000060
`

`08-18 02:05:22.271 E 18254    27200    KvsStream:                                                      [JNI] [DEV-STREAM-2] [H:1] [T:JNIKvsStream-dev1] kvsStreamErrorReportCallback Reported streamError callback for stream handle 510856029208. Upload handle 22. Fragment timecode in 100ns: 16607558900300000. Error status: 0x52000060`

`08-18 09:09:28.615 E 18254    28465    KvsStream:                                                      [JNI] [DEV-STREAM-2] [H:1] [T:JNIKvsStream-dev1] kvsStreamErrorReportCallback Reported streamError callback for stream handle 510856029208. Upload handle 56. Fragment timecode in 100ns: 16607813363150000. Error status: 0x52000060 `

**Device Infomation**
- OS: Android
- C Producer SDK (commit : 79da5b6), PIC (commit : afc15af)
- Receive video and audio via RTSP from the camera, but not using Gstreamer.

**Stream Infomation**

- Stream#1
    - Stream Name : A4
    - Stream Handle : 510858558296 (Reference when analyzing logs)
    - Video resolution : 720p
    - Video Codec : H.264, VBR
    - Max Bitrate : 768 kbps
    - Frame rate : 20 fps
    - I frame interval : 40
    - Audio Codec : AAC (sample rate : 16K)
  
- Stream#2 (**Problem stream**)
    - Stream Name : A5
    - Stream Handle : 510856029208 (Reference when analyzing logs)
    - Video resolution : 2048x1536
    - Video Codec : H.264, VBR
    - Max Bitrate : 2048 kbps
    - Frame rate : 20 fps
    - I frame interval : 40
    - Audio Codec : AAC (sample rate : 16K)
    
    I saw this issue, but honestly, I don't understand it well. 
    [https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/386](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/386)
    
    Why is 0x52000060 error occurring? 
    And why is there no data stored for tens of seconds at the time when the error occurred?

[Log_52000060_Error.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/9372331/Log_52000060_Error.zip)

**Comment by disa6302** [comment]
@Hanan-ob ,


The error indicates that the fragment timestamps are not monotonically increasing. The backend enforces monotonic increase in timestamps and if the consecutive frame timestamps are equal or the next frame timestamp is less than the previous, you would encounter this error. Along with that, I also see a couple of other things: defaultBufferDurationOverflowCallback gets invoked as well which indicates that your network is probably slow or dropped for the duration that causes the buffer to fill up leading to dropping of frames. I also see this: STATUS_ACK_TIMESTAMP_NOT_IN_VIEW_WINDOW (0x520000047). This means that by the time the Ack for the fragment is received, the fragment does not exist in the content view also indicating potential network pressures.

Investigate your network condition. Another thing you can do is try is increase the buffer duration to see if it alleviates this problem. The default is set to 20 seconds. You can set it by setting this property: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/afc15aff555090424d6b92ef316116e85004a479/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1020.

**Comment by disa6302** [comment]
Closing assuming answered. @Hanan-ob , feel free to reach out if you have any more questions.
