### ISSUE TITLE
Where is the source code for libkvsCommonLws?

### ISSUE THREAD

**Issue by assa-martin** [awslabs/amazon-kinesis-video-streams-producer-c#324]
I'm trying to debug a segfault, and it would be really useful if I could see the source code for this library, specifically I am looking for the source code implementation of `createStaticCredentialProvider`.

The library (libkvsCommonLws.a) is included in the `opensource/` folder, so one would naturally assume that source code should exist somewhere too -- I can't even find it searching google or github.

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/src/source/Common/StaticCredentialProvider.c

**Comment by assa-martin** [comment]
Excellent and thank you for the super speedy reply! So the search functions within github are still not that good then!
