### ISSUE TITLE
[FEATURE] Make `createDefaultCallbacksProviderWithFileAuth` better suited for cached credentials

### ISSUE THREAD

**Issue by mjdietzx** [awslabs/amazon-kinesis-video-streams-producer-c#326]
Related to #325

It is tough to use cached credentials properly w/ c producer lib currently. The first part of this issue would be resolved by #325, in the case cached credentials are already expired.

However, there is a case where credentials expire later, while streaming is on-going. This could be 12 hours into streaming, or in the case cached credentials are used, it could be eg `x` minutes into streaming

The problem here is it is really tough to refresh the credentials, and it does not happen automatically. The perfect api for cached credentials would be something like:

 - IoT device boots, credentials are cached, streaming starts immediately
 - a thread later gets new/fresh credentials and writes them to the `credentialsFilepath`
 - c producer lib automatically loads in these new credentials at some point (either on the first `curlCompleteSync(): HTTP Error 403 : Response: {"message":"The security token included in the request is expired"}` retry, or possibly more proactively)

The current behavior is even worse though due to some confusing behavior or `readFileCredentials` that I describe in #325. From that PR desc:
```
Basically these underlying functions do all the checks to see if credentials are expired, but allow expired credentials to be loaded (only if pFileCredentialProvider->pAwsCredentials is not set yet, once it's set expired credentials will not be loaded - basically readFileCredentials is a no-op in that case). 
```

That means that if I were to try to refresh the credential provider's credentials myself once I get new credentials, it would likely end up being a no-op, because the new credentials would ignored here https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/a8091d1a140fbdcb260ba3c8302aa2e4712d2d91/src/source/Common/FileCredentialProvider.c#L128, unless I happen to do it in the brief period of time `CREDENTIAL_FILE_READ_GRACE_PERIOD` before the credentials expire, or if I do it after they already expire. That doesn't seem ideal

**Comment by mjdietzx** [comment]
I dug around old issues a bit and found this explanation by @MushMal 

> KVS itself can stream indefinitely. It will simply update the credentials whenever it's needing it. Check your logs for the token rotation. Each KVS streaming session is up-to 40 minutes and the credentials will be rotated whenever a new session is established and whenever the credentials are about to expire.

I am wondering where I need to look or if there is any suggestion for me to get something like this in the case of file auth. I've had a lot of trouble finding where credentials are refreshed so anything helps. All I really need to do is read the credentials from file once, either before they expire or after streaming has started, because my credentials have 12 hour expiration and that is more than the longest we will ever stream. I just need to take care of an edge-case where cached credentials expire `x` minutes after they are first loaded

**Comment by MushMal** [comment]
Perhaps I am not understanding your scenario but file credentials usage is a very specialized case. If your actual credential provider is IoT then why not use the IoT credential provider? At any case, as long as the expiration is set correctly, the kvs producer will rotate the credentials prior to their expiration during what's known as "grace period" ~ 30 seconds prior if I am not mistaken. In case of long-lasting credentials, the file credentials can still be exactly the same and they would just get loaded again when the new session gets created. KVS can stream up-to around 40 mins and then it will have to create a new session. The credential provider will be queried for new credentials in case of a new session whether it's on rotation or on network hiccup.

The general use of file credential provider is when you have an out-of-bound credential refresher that periodically refreshes the file with new credentials with expiration in the future so the kvs producer will load fresh credentials whenever it's needing it

**Comment by bracki** [comment]
We face a similar problem. We are using dynamic AWS credentials (web socket and iot instead of certificates) that are provided via a custom implementation of [Aws::Auth::AWSCredentialsProvider](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_auth_1_1_a_w_s_credentials_provider.html). Currently it's very hard to update the credentials because they need to be written to a file and reloaded etc.
Generally it would be great if credentials wouldn't need to touch the file system at all and rather stay in memory.

**Comment by MushMal** [comment]
@bracki if your scenario is common then I would recommend describing it in details in an issue and community members would implement it. Adding a new credential provider is very simple once the interface is known. 

I would like to learn about how your application updates the piece in memory. It can be pretty straightforward but would be nice to describe the details. 

There was/is a test RotatingCredentialProvider thats used by the tests which can be used as a base for the in-memory credential provider.
