### ISSUE TITLE
[FEATURE] Mechanism to detect if stream is being consumed / watched live

### ISSUE THREAD

**Issue by mjdietzx** [awslabs/amazon-kinesis-video-streams-producer-c#330]
If we had a way to know if a stream is being played back / live-streamed that could potentially be a killer feature of c producer lib. Is this a realistic feature / very difficult? It would likely take effort from AWS/KVS to make this happen I'd assume.

There are a lot of possibilities if c producer lib has this info. One use case is the device automatically stops streaming if no one is watching. The use case I'm more interested in is the device dynamically changing behavior based on how the stream is being consumed. For my use case, if no one is watching live we can be much more aggressive with bandwidth (which is very limited for us) since frames will be back filled, and the video will be played back as an mp4, so the live-stream doesn't need to be smooth and glitches in the live stream will be corrected.

**Comment by disa6302** [comment]
@mjdietzx ,

While this will be a cool feature, it would not be possible to achieve this within the SDK. The current design does not have any interaction with consumer or does not depend on needing a consumer at all. And producer is flexible to work with any consumer. So this feature will have to be out of band in my opinion. 


About dynamic changes, with your out of band implementation of detecting presence of consumers, you could re-create the kinesis video client to set up the stream info params again - setting streaming mode to offline, increasing storage size to allow backfilling more frames, play around with buffer duration to allow more frames to be stored, etc.

**Comment by MushMal** [comment]
To my knowledge there isn't a simple mechanism to do this and there are technical reasons why it won't be a trivial task to implement on the service side given the massively distributed nature and the costs associated with it.

Instead, your application should handle the "messaging". Just thinking out about this, all you need is for a "viewer" to signal the  camera software to start streaming. This is a main scenario with WebRTC solutions and if I were to implement it I would look at the signaling solution from WebRTC which is a stand-alone library that can be used by your viewer to signal the camera which listens on the signaling channel to start streaming.

**Comment by mjdietzx** [comment]
Thank you for the response @disa6302 , @MushMal . Agreed on all counts and good suggestions. I am closing this issue as a feature like this is out-of-scope for c producer lib
