### ISSUE TITLE
[QUESTION] How to implement a refreshing credentials provider?

### ISSUE THREAD

**Issue by bracki** [awslabs/amazon-kinesis-video-streams-producer-c#332]
We want to implement a `DynamicCredentialsProvider` for use with that fetches credentials from somewhere. Once credentials expire the `getCredentialsFn` of our implementation should be called.
Imagine this [line](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L755) being replaced with `createDynamicCredentialsProvider`.

Apparently there are also various Callback classes, one for each credential provider and the global callback.

When using the Kinesis example from above, it seems the callbacks are never called?
The only call site is [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47/src/source/Signaling/StateMachine.c#L327).

What crucial part are we missing? Do we need to create the callbacks on our own? Or are they magically created for us?

Any guidance is appreciated.

(Also briefly touched this here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/326#issuecomment-1253386903)

**Comment by MushMal** [comment]
@bracki both WebRTC and Producer libraries share common library implementation. If you are using WebRTC then indeed, that's the place where the state automaton integrates with auth module. If you are using KVS Producer SDK then the location of integration is here https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/client/src/AuthIntegration.c#L24

Assuming you are using WebRTC then you might want to create your credentials provider and supply it to the signaling client which needs it like it's done in this line in the sample: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/blob/master/samples/Common.c#L1175

If you want to use the sample itself, either replace the line with static credential provider with your own or add another compiler definition which would if/else to dynamic credential provider you are trying to create.

Regarding the dynamic credential provider... The providers callback is called whenever fresh credentials are needed by the signaling client - either on startup or after reconnect or after expiration. You just need to implement the credentialProvider.getCredentialsFn API. I would recommend copying the code from one of the existing credential providers and modify it to point to your own function. If you have your own background thread to periodically fetch credentials then you might need to interlock it with the callback function. Your background thread would fetch the fresh AWS credentials and set an AwsCredentials internal object whereas the getCredentials would simply interlock and return the by-then fresh credentials.

**Comment by hassanctech** [comment]
@bracki Does that resolve your question?

**Comment by bracki** [comment]
@hassanctech @MushMal Yes it does. Excellent.
