### ISSUE TITLE
Compiler error `STATUS_CURL_PERFORM_FAILED` redefined (among others)

### ISSUE THREAD

**Issue by mitchellhansen-wyze** [awslabs/amazon-kinesis-video-streams-producer-c#334]
After updating to 1.4.0, I'm getting compiler errors due to a macro being redefined 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/1204f14081caf300b4e9bbb93e0a8824cb67cd22/src/include/com/amazonaws/kinesis/video/common/Include.h#L84

```
#define STATUS_CURL_PERFORM_FAILED                      STATUS_COMMON_BASE + 0x00000001
#define STATUS_IOT_INVALID_RESPONSE_LENGTH              STATUS_COMMON_BASE + 0x00000002
#define STATUS_IOT_NULL_AWS_CREDS                       STATUS_COMMON_BASE + 0x00000003
#define STATUS_IOT_INVALID_URI_LEN                      STATUS_COMMON_BASE + 0x00000004
```

These 4 are already defined on lines 53-56.

**Comment by hassanctech** [comment]
Not sure how this happened... looking into it!

**Comment by hassanctech** [comment]
New release has been cut with the fix:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/releases/tag/v1.4.1
