### ISSUE TITLE
[QUESTION] freeKinesisVideoStream api is hung (stuck)

### ISSUE THREAD

**Issue by Hanan-ob** [awslabs/amazon-kinesis-video-streams-producer-c#340]
**Describe Problem**

I have a problem where the freeKinesisVideoStream function hangs.

Problem Action Procedure

1. 0x15000025 error occurred - 09-20 05:20:05.992
    09-20 05:20:05.992 E 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamErrorReportCallback Reported streamError callback for stream handle 496622061272. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x15000025
    
2. 0x52000085 error occurs when putKinesisVideoFrame is running - 09-20 05:20:06.274
    09-20 05:20:06.274 W 3587 3889 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 16636188081233817 presentation timestamp: 16636188081233817
    
3. stop and release stream (If 0x52000085 error occurs during putKinesisVideoFrame, I implement to release the stream and start again.)
    09-20 05:20:06.395 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream
    09-20 05:20:06.395 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. stopKinesisVideoStreamSync
    09-20 05:20:06.395 I 3587 3739 kvsNdbg-KinesisVideoClient: stopKinesisVideoStreamSync(Synchronously stopping Kinesis Video Stream 00000073a0fb46d8.
    09-20 05:20:06.395 V 3587 3739 kvsNdbg-Stream: stopStreamSync(Awaiting for the stop stream to complete...
    09-20 05:20:11.396 E 3587 3739 kvsNdbg-Stream: stopStreamSync(Failed to stop Kinesis Video Stream - timed out.
    09-20 05:20:11.396 E 3587 3739 kvsNdbg-KinesisVideoClient: stopKinesisVideoStreamSync(operation returned status code: 0x0000000f
    09-20 05:20:11.396 E 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream Failed with status 0x0000000f
    09-20 05:20:11.397 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeDeviceInfo
    09-20 05:20:11.398 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeStreamInfoProvider
    09-20 05:20:11.399 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeKinesisVideoStream
    
4. freeKinesisVideoStream hung(stuck) forever

Log1 is the log where the problem occurred. 
Log2 is a log where 0x15000025 and 0x52000085 occur and stream is released but freeKinesisVideoStream hang problem does not occur.

**Log1** - freeKinesisVideoStream function hangs
09-20 05:20:05.010 E 3587 3889 kvsNdbg-CurlCall: blockingCurlCall(Curl perform failed for url https://...credentials with result Timeout was reached : Resolving timed out after 3000 milliseconds
09-20 05:20:05.012 D 3587 3889 kvsNdbg-StreamState: defaultStreamStateTransitionHook(Stream state machine retry count: 2
09-20 05:20:05.012 D 3587 3889 kvsNdbg-StreamState: defaultStreamStateTransitionHook(
09-20 05:20:05.012 D 3587 3889 kvsNdbg-StreamState: KinesisVideoStream base result is [10006]. Executing KVS retry handler of retry strategy type [1]
09-20 05:20:05.012 V 3587 3889 kvsNdbg-platform-utils: validateAndUpdateExponentialBackoffStatus(Current status is BACKOFF_IN_PROGRESS
09-20 05:20:05.012 V 3587 3889 kvsNdbg-platform-utils: getExponentialBackoffRetryStrategyWaitTime(
09-20 05:20:05.012 V 3587 3889 kvsNdbg-platform-utils: Thread Id [496196670704] Number of retries [3], Retry wait time [446] ms, Retry system time [16636188050122659]
09-20 05:20:05.012 V 3587 3889 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [5], State transition wait time [446] ms
09-20 05:20:05.012 V 3587 3889 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000040, Current local state retry count [13], Max local state retry count [0], State transition wait time [0] ms
09-20 05:20:05.985 V 3587 3889 kvsNdbg-Util: convertTimestampToEpoch(Expiration timestamp conversion into tm structure 122-8-19T21:20:8
09-20 05:20:05.986 D 3587 3889 kvsNdbg-Util: convertTimestampToEpoch(Difference between current time and iot expiration is 3603
09-20 05:20:05.986 D 3587 3889 kvsNdbg-IotCredentialProvider: parseIotResponse(Iot credential expiration time 1663622408
09-20 05:20:05.987 I 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamReadyCallback Reported streamReady callback for stream handle 496622061272
09-20 05:20:05.991 W 3587 3889 kvsNdbg-ContinuousRetryStreamCallbacks: continuousRetryStreamErrorReportHandler(Reporting stream error. Errored timecode: 0 Status: 0x15000025
09-20 05:20:05.991 D 3587 12127 kvsNdbg-CurlApiCallbacks: curlApiCallbacksShutdownActiveRequests(pActiveRequests hashtable is empty
09-20 05:20:05.992 E 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamErrorReportCallback Reported streamError callback for stream handle 496622061272. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x15000025
09-20 05:20:05.998 E 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKVSPM] kvsStreamErrorCb status: 0x00000200, kvsStatus: 0x15000025
09-20 05:20:06.007 E 3587 3889 kvsNdbg-KinesisVideoClient: getStreamingEndpointResultEvent(operation returned status code: 0x15000025
09-20 05:20:06.007 W 3587 3889 kvsNdbg-ContinuousRetryStreamCallbacks: continuousRetryStreamErrorReportHandler(Reporting stream error. Errored timecode: 0 Status: 0x15000025
09-20 05:20:06.009 E 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamErrorReportCallback Reported streamError callback for stream handle 496622061272. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x15000025
09-20 05:20:06.023 V 3587 12097 kvsNdbg-Response: postReadCallback(Get Stream data returned: buffer size: 65524 written bytes: 0 for upload handle: 704 current stream handle: 496622061272
09-20 05:20:06.023 W 3587 3889 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(Failed to submit frame to Kinesis Video client. status: 0x15000025 decoding timestamp: 16636188019913817 presentation timestamp: 16636188019913817
09-20 05:20:06.023 W 3587 3889 JNIKvsStream: [Stream-P03] [RTM:0] kvsStreamPutAudioFrame. CleanUp. hNum: 0, 0x15000025, streamHandle: 496622061272
09-20 05:20:06.024 W 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamPutAudioFrame Audio PutFraem Error: 0x15000025 cnt:0, streamHandle: 496622061272
09-20 05:20:06.274 V 3587 3889 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(debug frame info stream handle: 496622061272, index: 7476220, pts: 16636188081233817, dts: 16636188081233817, duration: 0, size: 251, trackId: 2, isKey 0
09-20 05:20:06.274 W 3587 3889 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 16636188081233817 presentation timestamp: 16636188081233817
09-20 05:20:06.274 W 3587 3889 JNIKvsStream: [Stream-P03] [RTM:0] kvsStreamPutAudioFrame. CleanUp. hNum: 0, 0x52000085, streamHandle: 496622061272
09-20 05:20:06.274 W 3587 3889 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamPutAudioFrame Audio PutFraem Error: 0x52000085 cnt:0, streamHandle: 496622061272
09-20 05:20:06.275 V 3587 3890 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(debug frame info stream handle: 496622061272, index: 9569004, pts: 16636188042213817, dts: 16636188042213817, duration: 0, size: 6159, trackId: 1, isKey 0
09-20 05:20:06.394 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKVSPM] setKvspState state: 1, old state: 5
09-20 05:20:06.394 I 3587 3739 UAUKVS_KvsStream: [Stream-P03] hNum[0] kvspStateCallback. state: 1, KVS_RUN, old state: 5, ERROR
09-20 05:20:06.395 D 3587 3739 JNIKvsStream: hNum[0] releaseKvsStream.
09-20 05:20:06.395 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream
09-20 05:20:06.395 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. stopKinesisVideoStreamSync
09-20 05:20:06.395 I 3587 3739 kvsNdbg-KinesisVideoClient: stopKinesisVideoStreamSync(Synchronously stopping Kinesis Video Stream 00000073a0fb46d8.
09-20 05:20:06.395 V 3587 3739 kvsNdbg-Stream: stopStreamSync(Awaiting for the stop stream to complete...
09-20 05:20:11.396 E 3587 3739 kvsNdbg-Stream: stopStreamSync(Failed to stop Kinesis Video Stream - timed out.
09-20 05:20:11.396 E 3587 3739 kvsNdbg-KinesisVideoClient: stopKinesisVideoStreamSync(operation returned status code: 0x0000000f
09-20 05:20:11.396 E 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream Failed with status 0x0000000f
09-20 05:20:11.397 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeDeviceInfo
09-20 05:20:11.398 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeStreamInfoProvider
09-20 05:20:11.399 I 3587 3739 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] releaseKvsStream. freeKinesisVideoStream
09-20 05:20:11.400 I 3587 3739 kvsNdbg-KinesisVideoClient: freeKinesisVideoStream(Freeing Kinesis Video stream.
09-20 05:20:11.400 W 3587 3739 kvsNdbg-CurlApiCallbacks: shutdownStreamCurl(shutdownStreamCurl called when already in progress of shutting down
09-20 05:20:16.200 I 3587 12127 UAUKVS_KvsStream: [JNI] [Stream-P03] [H:0] [RTM:false] [T:JNIKvsStream] kvsStreamShutdownCallback Reported streamShutdown callback for stream handle 496622061272, resetStream: 1

**Log2** - freeKinesisVideoStream function doen’t  hang
09-26 11:03:14.759 E 3587 3905 kvsNdbg-CurlCall: blockingCurlCall(Curl perform failed for url https://.../credentials with result Timeout was reached : Resolving timed out after 3000 milliseconds
09-26 11:03:14.760 D 3587 3905 kvsNdbg-StreamState: defaultStreamStateTransitionHook(Stream state machine retry count: 15
09-26 11:03:14.760 D 3587 3905 kvsNdbg-StreamState: defaultStreamStateTransitionHook(
09-26 11:03:14.760 D 3587 3905 kvsNdbg-StreamState: KinesisVideoStream base result is [10006]. Executing KVS retry handler of retry strategy type [1]
09-26 11:03:14.760 V 3587 3905 kvsNdbg-platform-utils: validateAndUpdateExponentialBackoffStatus(Current status is BACKOFF_IN_PROGRESS
09-26 11:03:14.760 V 3587 3905 kvsNdbg-platform-utils: resetExponentialBackoffRetryState(Thread Id [496072905968]. Resetting Exponential Backoff State. Last retry system time [16641573984869578], retry count so far [15], Current system time [16641577947605029]
09-26 11:03:14.760 V 3587 3905 kvsNdbg-platform-utils: getExponentialBackoffRetryStrategyWaitTime(
09-26 11:03:14.760 V 3587 3905 kvsNdbg-platform-utils: Thread Id [496072905968] Number of retries [1], Retry wait time [113] ms, Retry system time [16641577947604985]
09-26 11:03:14.760 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000010, Current local state retry count [1], Max local state retry count [5], State transition wait time [113] ms
09-26 11:03:14.760 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000002, Current local state retry count [0], Max local state retry count [5], State transition wait time [0] ms
09-26 11:03:14.799 W 3587 22103 kvsNdbg-Response: curlCompleteSync(curl perform failed for url https://...putMedia with result Timeout was reached: Resolving timed out after 5000 milliseconds
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: curlCompleteSync(HTTP Error 0 : Response: (null)
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: Request URL: https://.../putMedia
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: Request Headers:
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: Authorization: ...
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: connection: keep-alive
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: content-type: application/json
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: host: ....amazonaws.com
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: transfer-encoding: chunked
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: user-agent:
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: X-Amz-Date:
09-26 11:03:14.800 W 3587 22103 kvsNdbg-Response: x-amz-security-token:
09-26 11:03:14.800 D 3587 22103 kvsNdbg-CurlApiCallbacks: putStreamCurlHandler(Network thread for Kinesis Video stream: USEN_KVS_999220301_TEST_205000021_A1 with upload handle: 963 exited. http status: 0
09-26 11:03:14.801 W 3587 22103 kvsNdbg-CurlApiCallbacks: putStreamCurlHandler(Stream with streamHandle 496100069080 uploadHandle 963 has exited without triggering end-of-stream. Service call result: 599
09-26 11:03:14.801 I 3587 22103 kvsNdbg-KinesisVideoClient: kinesisVideoStreamTerminated(Stream 0x7381de4ed8 terminated upload handle 963 with service call result 599.
09-26 11:03:15.800 V 3587 3905 kvsNdbg-Util: convertTimestampToEpoch(Expiration timestamp conversion into tm structure 122-8-26T3:3:19
09-26 11:03:15.800 D 3587 3905 kvsNdbg-Util: convertTimestampToEpoch(Difference between current time and iot expiration is 3604
09-26 11:03:15.800 D 3587 3905 kvsNdbg-IotCredentialProvider: parseIotResponse(Iot credential expiration time 1664161399
09-26 11:03:15.800 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000002, Next state: 0x0000000000000040, Current local state retry count [0], Max local state retry count [0], State transition wait time [0] ms
09-26 11:03:15.800 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000010, Next state: 0x0000000000000040, Current local state retry count [0], Max local state retry count [5], State transition wait time [0] ms
09-26 11:03:15.801 I 3587 3905 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamReadyCallback Reported streamReady callback for stream handle 496100069080
09-26 11:03:15.804 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000080, Current local state retry count [0], Max local state retry count [0], State transition wait time [0] ms
09-26 11:03:15.804 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000040, Next state: 0x0000000000000040, Current local state retry count [1], Max local state retry count [0], State transition wait time [0] ms
09-26 11:03:15.805 I 3587 3905 kvsNdbg-KinesisVideoClient: putStreamResultEvent(Put stream result event. New upload handle 964
09-26 11:03:15.805 V 3587 3905 kvsNdbg-Response: notifyDataAvailable(Note data received: duration(100ns): 358660000 bytes 628783 for stream handle 964
09-26 11:03:15.815 V 3587 3905 kvsNdbg-StreamCallbacksProvider: defaultStreamDataAvailableCallback(Reported streamDataAvailable callback for stream handle 496100069080. Upload handle 964. Duration available in 100ns: 358660000. Bytes available: 628783
09-26 11:03:15.815 V 3587 3905 kvsNdbg-State: stepStateMachine(State Machine - Current state: 0x0000000000000080, Next state: 0x0000000000000100, Current local state retry count [0], Max local state retry count [0], State transition wait time [0] ms
09-26 11:03:15.815 W 3587 3905 kvsNdbg-ContinuousRetryStreamCallbacks: continuousRetryStreamErrorReportHandler(Reporting stream error. Errored timecode: 0 Status: 0x15000025
09-26 11:03:15.817 D 3587 22122 kvsNdbg-CurlApiCallbacks: curlApiCallbacksShutdownActiveRequests(pActiveRequests hashtable is empty
09-26 11:03:15.819 E 3587 3905 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamErrorReportCallback Reported streamError callback for stream handle 496100069080. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x15000025
09-26 11:03:15.828 W 3587 3905 kvsNdbg-ContinuousRetryStreamCallbacks: continuousRetryStreamErrorReportHandler(Reporting stream error. Errored timecode: 0 Status: 0x15000025
09-26 11:03:15.829 E 3587 3905 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamErrorReportCallback Reported streamError callback for stream handle 496100069080. Upload handle 18446744073709551615. Fragment timecode in 100ns: 0. Error status: 0x15000025
09-26 11:03:15.843 W 3587 3905 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(Failed to submit frame to Kinesis Video client. status: 0x15000025 decoding timestamp: 16641577558450918 presentation timestamp: 16641577558450918
09-26 11:03:15.844 W 3587 22091 kvsNdbg-StreamEvent: streamTerminatedEvent(Last fragment with timestamp 18446744073709551615 for upload handle 962 might not be fully persisted
09-26 11:03:15.844 W 3587 3905 JNIKvsStream: [Stream-P01] [RTM:1] kvsStreamPutVideoFrame. CleanUp. hNum: 2, 0x15000025, streamHandle: 496100069080
09-26 11:03:15.844 V 3587 22091 kvsNdbg-StreamCallbacksProvider: defaultStreamDataAvailableCallback(Reported streamDataAvailable callback for stream handle 496100069080. Upload handle 964. Duration available in 100ns: 0. Bytes available: 0
09-26 11:03:15.844 W 3587 22103 kvsNdbg-StreamEvent: streamTerminatedEvent(Last fragment with timestamp 18446744073709551615 for upload handle 963 might not be fully persisted
09-26 11:03:15.844 V 3587 22103 kvsNdbg-StreamCallbacksProvider: defaultStreamDataAvailableCallback(Reported streamDataAvailable callback for stream handle 496100069080. Upload handle 964. Duration available in 100ns: 0. Bytes available: 0
09-26 11:03:15.844 W 3587 22081 kvsNdbg-StreamEvent: streamTerminatedEvent(Last fragment with timestamp 18446744073709551615 for upload handle 961 might not be fully persisted
09-26 11:03:15.845 V 3587 22081 kvsNdbg-StreamCallbacksProvider: defaultStreamDataAvailableCallback(Reported streamDataAvailable callback for stream handle 496100069080. Upload handle 964. Duration available in 100ns: 0. Bytes available: 0
09-26 11:03:15.845 W 3587 3905 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamPutVideoFrame Video PutFraem Error: 0x15000025, cnt:0, streamHandle: 496100069080
09-26 11:03:15.907 W 3587 3905 kvsNdbg-KinesisVideoClient: putKinesisVideoFrame(Failed to submit frame to Kinesis Video client. status: 0x52000085 decoding timestamp: 16641577593940918 presentation timestamp: 16641577593940918
09-26 11:03:15.907 W 3587 3905 JNIKvsStream: [Stream-P01] [RTM:1] kvsStreamPutVideoFrame. CleanUp. hNum: 2, 0x52000085, streamHandle: 496100069080
09-26 11:03:16.002 I 3587 3864 JNIKVSPM: Stream-P01 hNum[2], stopKvsProducer
09-26 11:03:16.067 D 3587 3864 JNIKvsStream: hNum[2] releaseKvsStream.
09-26 11:03:16.067 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream
09-26 11:03:16.068 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. stopKinesisVideoStreamSync
09-26 11:03:16.096 V 3587 3864 kvsNdbg-Stream: stopStreamSync(Awaiting for the stop stream to complete...
09-26 11:03:16.219 I 3587 22122 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamShutdownCallback Reported streamShutdown callback for stream handle 496100069080, resetStream: 1
09-26 11:03:18.740 I 3587 22145 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamReadyCallback Reported streamReady callback for stream handle 496100069080
09-26 11:03:21.100 E 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream Failed with status 0x0000000f
09-26 11:03:21.100 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. freeDeviceInfo
09-26 11:03:21.101 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. freeStreamInfoProvider
09-26 11:03:21.101 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. freeKinesisVideoStream
09-26 11:03:28.811 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] kvsStreamShutdownCallback Reported streamShutdown callback for stream handle 496100069080, resetStream: 0
09-26 11:03:28.812 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. freeKinesisVideoClient
09-26 11:03:29.215 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream. freeCallbacksProvider
09-26 11:03:29.216 I 3587 3864 UAUKVS_KvsStream: [JNI] [Stream-P01] [H:2] [RTM:true] [T:JNIKvsStream] releaseKvsStream . released resource

**SDK version number**
C Producer SDK (commit : [[79da5b6](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/commit/79da5b6d6ad67560cc08530f967e9187a6d1c594)](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/commit/79da5b6d6ad67560cc08530f967e9187a6d1c594)), PIC (commit : afc15af)

**To Reproduce**
It happens intermittently.

**Expected behavior**
Application shouldn't hang in freeKinesisVideoStream api call.
Or can you give me a guide to avoid this problem?

[log1_ freeKinesisVideoStream_function_hangs.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/9818818/log1_.freeKinesisVideoStream_function_hangs.zip)
[Log2_freeKinesisVideoStream_function_doen’t_ hang.zip](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/9818821/Log2_freeKinesisVideoStream_function_doen.t_.hang.zip)

**Comment by hassanctech** [comment]
Can you please try with the latest release:  https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/releases/tag/v1.4.1

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen / raise a new issue
