### ISSUE TITLE
[BUG] `blockingCurlCall` segfaulted when handling (rare) error-case

### ISSUE THREAD

**Issue by mjdietzx** [awslabs/amazon-kinesis-video-streams-producer-c#341]
Seems to be a very rare issue, haven't seen it before. But during tested I noticed a sec-fault when an http request failed w/ error: `Device or resource busy`

```
2022-10-20 22:52:04 ERROR   blockingCurlCall(): Curl perform failed for[   13.000000] do_page_fault(): sending SIGSEGV to stream for invalid read access from 7ceaf2ac
 url <URL_OBSCURED>[   13.040000] epc = 77608bc8 in with result  libuClibc-1.0.31.so[775ad000+a1000]Error : er
ro[   13.056000] ra  = 77608b3c inr:0200E010:system library:setsocko libuClibc-1.0.31.so[775ad000+a1000]pt:Devi
ce or resource busy
```

I think this is the specific line that failed, this function also may have returned and `Cleanup` may have ran (I'm trying to debug that now)
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/80c74ac9200b58427a8fcb7782a03b1774020983/src/source/Common/Curl/CurlCall.c#L79

I am investigating but have not made progress at finding what went wrong, and will likely not be able to reproduce this issue since it is so rare. I am on an embedded mips linux device but I don't think it's so relevant to this issue

**Comment by jdelapla** [comment]
Strange to see a log message fully printed out and a segfault print fighting over the buffer. Is this a multi-process application?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to reopen in case of further questions
