### ISSUE TITLE
[QUESTION]fragment decoding error in player

### ISSUE THREAD

**Issue by fugudong** [awslabs/amazon-kinesis-video-streams-producer-c#342]
Hi, in our project, we create three stream that push video and audio by using kvs producer c library. 
We have two projects with different soc. 
The first project's first and second stream is normal, but third stream has fragment decoding error. 
and the second project's first and second stream has fragment decoding error, but the third stream is normal。
In two projects, if only push video, all three streams are normal.

Can you give me advice about this error, thanks.

**Comment by jdelapla** [comment]
Hello @fugudong , could you specify the exact fragment decoding error you mention, as well as provide some contextual logs?
