### ISSUE TITLE
[QUESTION]mkvgenPackageFrame(): Warning: Failed auto-extracting the CPD from the key frame

### ISSUE THREAD

**Issue by fugudong** [awslabs/amazon-kinesis-video-streams-producer-c#343]
When I push H264 frame from MP4 Dmux, I have following log about  issue,
2022-11-23 02:48:16 WARN    mkvgenPackageFrame(): Warning: Failed auto-extracting the CPD from the key frame.
2022-11-23 02:48:16 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x3200000d decoding timestamp: 120104790 presentation timestamp: 120104790

If i push H264 frame from H264 encoder, i can push frame to amazon successfully.

so the I frame from MP4 Dmux is different from H264 encoder, what info i should provide when i push frame from MP4 Dmux to amazon server, thanks.

**Comment by fugudong** [comment]
Do you mean we can provide video codecPrivateData to fix this issue  like the api mkvgenGenerateAacCpd that generate audio codecPrivateData.
Yes, the frame resolution is 848x480, and the fps is 30. 
Please also help provide codecPrivateData for h265, thanks.

**Comment by jdelapla** [comment]
Can you share the video you're trying to upload so we can analyze the frame that failed.

**Comment by hassanctech** [comment]
Closing due to lack of response.  @fugudong if you are still experiencing issues please open a new issue (or re-open this one) **with the requested information by @jdelapla **
