### ISSUE TITLE
[QUESTION] How do I adapt AAC audio fragments?

### ISSUE THREAD

**Issue by sam-vasiutin** [awslabs/amazon-kinesis-video-streams-producer-c#346]
I am currently working on streaming application from iOS devices and I was able to successful run stream using `video only` format. I used h265 frames adapted with NALu headers (SPS, VPS and PPS) for video data.

Now I need to run `audioVideo` stream, but I can't understand how to adapt audio.
As I saw in another question, producer doesn't accept AAC with ADTS headers, what do I use instead then?

**Comment by sam-vasiutin** [comment]
Do I even need to adapt audio data, or it can be just passed to producer with specifying CPD for audio track info object?
Cause this is how it is done in sample for the AAC.

**Comment by sam-vasiutin** [comment]
@MushMal Could you some help?

**Comment by sam-vasiutin** [comment]
@MushMal Could you some help?

**Comment by MushMal** [comment]
There are two aspects to the question. 1) KVS will accept any data in any format really as long as your producer and consumer agree upon it. 2) The only time when KVS will be concerned with the format/data is when you use KVS consumers - for example the media APIs like HLS/DASH or a console playback. This is the time when you need to adapt to the KVS playback specification. Perhaps someone from KVS will chime in but the stream has to be a multi-track which includes primary video and an audio track. There are some samples on the multi-track. I don't remember the details but for AAC you don't need to adapt the elementary audio stream. @hassanctech do you have more data on this?

**Comment by sam-vasiutin** [comment]
> There are two aspects to the question. 1) KVS will accept any data in any format really as long as your producer and consumer agree upon it. 2) The only time when KVS will be concerned with the format/data is when you use KVS consumers - for example the media APIs like HLS/DASH or a console playback. This is the time when you need to adapt to the KVS playback specification. Perhaps someone from KVS will chime in but the stream has to be a multi-track which includes primary video and an audio track. There are some samples on the multi-track. I don't remember the details but for AAC you don't need to adapt the elementary audio stream. @hassanctech do you have more data on this?

This is the point, I am using HLS API and console for playback, currently I am just passing raw compressed audio data and have no clue how to get it working. In console it says either `Missing codec private data error` if I don't specify cpd in `StreamInfoProvider.C`, or just infinite searching for media if specify cpd(found some hardcoded value of "1588" in other topic) for audioTrack.
BTW, for video I am not specifying cpd, but just compressing video frames and adding NALu and it works for video-only streaming.

So, what I can suggest doing - to either not specifying cpd for audioTrack and somehow adapting audio data with ADTS/NALu (Thought NALu is only for video data, but I'll give it a try) or just passing raw compressed data for audio and finding correct cpd.

No cpd, raw compressed AAC frames:
<img width="959" alt="Missing codec private data error" src="https://user-images.githubusercontent.com/107999083/214799843-97f662aa-29db-4a30-a610-12d23052bdf4.png">

CPD "1588", raw compressed AAC frames:
<img width="1183" alt="Infinite loading when specifying cpd" src="https://user-images.githubusercontent.com/107999083/214799774-636dd96a-8d4d-4ea1-b385-26e46f4351be.png">

**Comment by sam-vasiutin** [comment]
Researching the audio coding I found out how to calculate cpd for audio.
To get cpd I am using `mkvgenGenerateAacCpd` function which gives me `1208`:

```
AAC_LC = 2 = 00010
44100 hz = 4 = 0100
1 channel = 0001

0001001000001000(binary) = 1208(hex)
```
So after I set cpd to `1208` and now it's just infinite "Searching for media" in playback console.


The only place where could be an error is audio formatting, since I am receiving audio in kAudioFormatLinearPCM and converting it to kAudioFormatMPEG4AAC (AAC_LC) using AVAssetWriter with predefined output settings.
I'll try working on this part.

**Comment by MushMal** [comment]
Some of the details escape my memory but there are a couple of useful helpers in PIC: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/c8325887faa3a4a296c4367b281c778be69875b6/src/mkvgen/src/MkvGenerator.c#L1735

Perhaps, trying some synthetic AAC to ensure e2e works would be a good start?

**Comment by sam-vasiutin** [comment]
I was able to get this working, the audio is a bit off sync, but I will handle this.
In total, I needed specify cpd calculated by `mkvgenGenerateAacCpd` function when create a stream and to convert audio source from pcm to compressed aac (using AudioToolbox API), pretty straitforward.

And yes, ADTS is not needed.
