### ISSUE TITLE
Understanding the framerate parameter

### ISSUE THREAD

**Issue by xiaopengfei-hl** [awslabs/amazon-kinesis-video-streams-producer-c#353]
struct __StreamCaps {
    STREAMING_TYPE streamingType;
    CHAR contentType[MAX_CONTENT_TYPE_LEN + 1];
    BOOL adaptive;
    UINT64 maxLatency;
    UINT64 fragmentDuration;
    BOOL keyFrameFragmentation;
    BOOL frameTimecodes;
    BOOL absoluteFragmentTimes;
    BOOL fragmentAcks;
    BOOL recoverOnError;
    UINT32 nalAdaptationFlags;
    UINT32 frameRate;
    UINT64 bufferDuration;
    UINT64 replayDuration;
    UINT64 connectionStalenessDuration;
    UINT64 timecodeScale;
    BOOL recalculateMetrics;
    PBYTE segmentUuid;
    PTrackInfo trackInfoList;
    UINT32 trackInfoCount;
    FRAME_ORDER_MODE frameOrderingMode;
    CONTENT_STORE_PRESSURE_POLICY storePressurePolicy;
    CONTENT_VIEW_OVERFLOW_POLICY viewOverflowPolicy;
};
UINT32 frameRate;
How to understand this parameter？Audio plus video？What is the impact of comparing the values of the framerate parameter？

**Comment by sirknightj** [comment]
Hi @xiaopengfei-hl , thanks for your question. If I understand correctly, you are asking about how `framerate` is used.
The `framerate` parameter only applies to video. The units are in frames per second (fps).
