### ISSUE TITLE
[BUG] 执行./kvsVideoOnlyRealtimeStreamingSample myTest h265报错

### ISSUE THREAD

**Issue by zhangshouyin** [awslabs/amazon-kinesis-video-streams-producer-c#414]
配置：
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake .. -DMEMORY_SANITIZER=TRUE

export AWS_SECRET_ACCESS_KEY=“xxxxx”
export AWS_ACCESS_KEY_ID="xxx....xxxxx"

我在执行./kvsVideoOnlyRealtimeStreamingSample myTest h265报错

root@ip-172-31-39-215:/home/ubuntu/amazon-kinesis-video-streams-producer-c/build# ./kvsVideoOnlyRealtimeStreamingSample myTest h265 

Uninitialized bytes in __interceptor_fopen64 at offset 0 inside [0x705000000000, 77)
==4816==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fde62eb366a in BIO_new_file (/home/ubuntu/amazon-kinesis-video-streams-producer-c/open-source/lib/libcrypto.so.1.1+0xb366a) (BuildId: eadff5c2de65ea21bddec5c6860fe0eb2d7695e2)
    #1 0x7fde62ee951d in def_load conf_def.c
    #2 0x7fde62eeabac in CONF_modules_load_file (/home/ubuntu/amazon-kinesis-video-streams-producer-c/open-source/lib/libcrypto.so.1.1+0xeabac) (BuildId: eadff5c2de65ea21bddec5c6860fe0eb2d7695e2)
    #3 0x7fde635057a7 in Curl_ossl_init openssl.c
    #4 0x7fde6350d250 in Curl_ssl_init (/home/ubuntu/amazon-kinesis-video-streams-producer-c/open-source/lib/libcurl.so+0x6f250) (BuildId: cbde7239ac707b390d1c0895ee8b7ac7a85c03d9)
    #5 0x7fde634cd183 in global_init easy.c
    #6 0x7fde634cd200 in curl_global_init (/home/ubuntu/amazon-kinesis-video-streams-producer-c/open-source/lib/libcurl.so+0x2f200) (BuildId: cbde7239ac707b390d1c0895ee8b7ac7a85c03d9)
    #7 0x7fde63248458 in createCurlApiCallbacks /home/ubuntu/amazon-kinesis-video-streams-producer-c/src/source/CurlApiCallbacks.c:140:5
    #8 0x7fde6321a467 in createAbstractDefaultCallbacksProvider /home/ubuntu/amazon-kinesis-video-streams-producer-c/src/source/CallbacksProvider.c:329:5
    #9 0x7fde6321bf5f in createDefaultCallbacksProviderWithAwsCredentials /home/ubuntu/amazon-kinesis-video-streams-producer-c/src/source/CallbacksProvider.c:76:5
    #10 0x5642be6fc5c7 in main /home/ubuntu/amazon-kinesis-video-streams-producer-c/samples/KvsVideoOnlyRealtimeStreamingSample.c:125:5
    #11 0x7fde62a29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: a43bfc8428df6623cd498c9c0caeb91aec9be4f9)
    #12 0x7fde62a29e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: a43bfc8428df6623cd498c9c0caeb91aec9be4f9)
    #13 0x5642be6743d4 in _start (/home/ubuntu/amazon-kinesis-video-streams-producer-c/build/kvsVideoOnlyRealtimeStreamingSample+0x1e3d4) (BuildId: 6745adbcbf1bad2fd161a5d830c4258daf675efb)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/ubuntu/amazon-kinesis-video-streams-producer-c/open-source/lib/libcrypto.so.1.1+0xb366a) (BuildId: eadff5c2de65ea21bddec5c6860fe0eb2d7695e2) in BIO_new_file
Exiting

这个错误 不清楚是 什么原因？

**Comment by disa6302** [comment]
@zhangshouyin ,

We do not have control over the errors in our dependencies. Any reason you are running with MEMORY_SANITIZER enabled?

**Comment by niyatim23** [comment]
Closing due to no response
