### ISSUE TITLE
[QUESTION]What is the difference between createKinesisVideoStreamSync and createKinesisVideoStream

### ISSUE THREAD

**Issue by fugudong** [awslabs/amazon-kinesis-video-streams-producer-c#418]
In our project, we find the function createKinesisVideoStreamSync exec time is related to network status ,  and we replace createKinesisVideoStreamSync with createKinesisVideoStream,  our project can work, and the createKinesisVideoStream exec time is shorter and not related to network status.
So i want to know the difference between createKinesisVideoStreamSync and createKinesisVideoStream, can wo replace in this way.

**Comment by MushMal** [comment]
These APIs perform various tasks ranging from validity checks to creating the local resources and buffers to performing actual API calls. At the core, the API is entirely asynchronous (the non-SYNC prefixed API). The PIC state machine will cycle through the states and "yield" on any API calls or other callback calls. The state machine will only continue when the call resolves. The state machine is driven by the callbacks and responses to the callbacks.
The SYNC version of the API is there as a convenience and it orchestrates the entire state machine calls in a synchronous fashion. More advanced applications which are designed to benefit from the asynchronous API model can use the async API to gain liveliness and performance. In fact, the SYNC version of the API is nothing but the orchestrator over the core ASYNC API and you can trace the calls and the implementation and model yours after it.

**Comment by fugudong** [comment]
ok,thanks
