### ISSUE TITLE
Failed to submit frame to Kinesis Video client. status: 0x52000085

### ISSUE THREAD

**Issue by WeiWei00123** [awslabs/amazon-kinesis-video-streams-producer-c#425]
I try to push my audio and video from my ip cam to KVS, refer to [KvsAudioVideoStreamingSample.c](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsAudioVideoStreamingSample.c) sample code, but encounter this error "Failed to submit frame to Kinesis Video client. status: 0x52000085",I also try [KvsAudioOnlyStreamingSample.c](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsAudioOnlyStreamingSample.c) and [KvsVideoOnlyRealtimeStreamingSample.c](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsVideoOnlyRealtimeStreamingSample.c) both work suessfully. Here are the audio and video settings:

Video Settings:
- format:h264 
- fps:25
- video size:1920x1080 

Audio Settings:
- format:AAC
-  sample rate: 48000

- Frame Configuration:

  ============init=================================
                audio frame duration : 200000        video frame duration : 400000
                audio frame decodingTs : 0             video frame decodingTs : 0
                audio frame presentationTs : 0        video frame presentationTs : 0
                audio frame index : 0
  ============setting===============================
                audio frame.presentationTs += audio frame.duration;
                audio frame.decodingTs = audio frame.presentationTs;
                audio frame.index++;
                vidoe frame.presentationTs += vidoe frame.duration;
                vidoe frame.decodingTs = vidoe frame.presentationTs;
                vidoe frame.index++;

- sdk version
1.5.1

here is my log file
[log.txt](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/files/13596876/log.txt)

```[tasklist]
### Tasks
```

**Comment by hassanctech** [comment]
The error you're seeing `0x52000085` translates to `STATUS_MAX_FRAME_TIMESTAMP_DELTA_BETWEEN_TRACKS_EXCEEDED`.  This error is thrown when you multiple tracks (i.e audio track and video track) and you exceed a predefined maximum distance between the latest from on one track vs the other track.  For our SDK this predefined maximum distance is 60 frames.

For example if your audio track is receiving frames and has received 60 frames and in that time *NO* video frames were received, then you will throw this error.  Typically this error is received when a track just stops producing frames.  Can you verify from your media source that both frames are producing frames?  You can print verbose logging which will log each call to put frame and also print the track number with a timestamp so you can see for yourself if this is happening.

**Comment by disa6302** [comment]
Closing due to no response. Feel free to reopen / open a new issue if this is still an issue.
