### ISSUE TITLE
curl perform failed when running to connect RTSPSRC using Iot certificate

### ISSUE THREAD

**Issue by deorwine** [awslabs/amazon-kinesis-video-streams-producer-c#433]
[WARN ] [18-01-2024 11:03:03:073.708 GMT] curlCompleteSync(): [camera_101] curl perform failed for url https://s-d022f287.kinesisvideo.us-east-1.amazonaws.com/putMedia with result Timeout was reached: Operation too slow. Less than 30 bytes/sec transferred the last 30 seconds
[WARN ] [18-01-2024 11:03:03:074.194 GMT] curlCompleteSync(): [camera_101] HTTP Error 0 : Response: (null)

**Comment by disa6302** [comment]
@deorwine ,

It seems your putMedia is failing because of no data. To debug this, you can run some tests to confirm the rtsp source is working and generating frames. You could either do this using a VLC player or even setting up a simple gstreamer pipeline with autovideosink.

**Comment by deorwine** [comment]
i have used it on VLC player and it is working perectly rtsp://admin:Test@72.250.61.203:554/11   
but not  working with gstreemer to kvssink
