### ISSUE TITLE
[Question] Why am I getting "Iot credential  Failed with status 0x15000020"?

### ISSUE THREAD

**Issue by RTL8710** [awslabs/amazon-kinesis-video-streams-producer-c#449]
**Media pipeline:**
kvsAudioVideoStreamingSample

**Logging**
Loading audio frames...
Done loading audio frames.
Loading video frames...
Done loading video frames.
pSampleConfiguration->pCaCertPath = /home/kunlunbp/embedApplication/aws_iot_sdk_embeded/root-CA.crt
pIotCoreCredentialEndPoint = cah7l82f9wtsm.credentials.iot.us-east-2.amazonaws.com
pIotCoreCert = /home/kunlunbp/embedApplication/aws_iot_sdk_embeded/00000000-0000-0000-0000-000000000009.pem.crt 
pIotCorePrivateKey = /home/kunlunbp/embedApplication/aws_iot_sdk_embeded/00000000-0000-0000-0000-000000000009.pem.key 
pIotCoreRoleAlias = ipcamera_event_rule_alias
pIotCoreThingName = 00000000-0000-0000-0000-000000000009
Failed with status 0x15000020

**Describe the bug**
 Iot credential  error

**SDK version number**
1.5.2

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by disa6302** [comment]
The error code indicates that an invalid path is provided to ca cert. Please ensure a ca cert actually exists in the path.

**Comment by RTL8710** [comment]
where is ca cert path ?

**Comment by RTL8710** [comment]
cat /home/kunlunbp/embedApplication/aws_iot_sdk_embeded/
root-CA.crt
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----

**Comment by RTL8710** [comment]
Could you please advise me on how to view error codes?

**Comment by disa6302** [comment]
@RTL8710 ,

The error codes are usually defined in the header files Include.h. Here is the definition for the error code you encountered: 

https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/v1.5.2/src/include/com/amazonaws/kinesis/video/common/Include.h#L49

**Comment by sirknightj** [comment]
The CA certificate needs to end with `.pem`, not `.crt`. You will need to rename the file.

```
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/3e519b7670e39031375d227f983ad2cde888078e/src/source/Common/Curl/CurlCall.c#L45-L46
```

**Comment by hassanctech** [comment]
@RTL8710 If you change the extension to `.pem` your issue should be resolved.  Please re-open this ticket if you continue to need assistance on the same issue.

**Comment by RTL8710** [comment]
The path to the encrypted file has been modified and the issue has been resolved. Thank you very much

**Comment by RTL8710** [comment]
I'm currently integrating KVS WebRTC and KVS Producer together and encountered some issues:

Issue 1: Incompatibility with mbedtls version. The latest WebRTC version 1.10.2 uses mbedtls version 2.25.0.

Issue 2: Whether to use lws (libwebsockets) or curl.

Is there a quick way to merge KVS and Producer into a single project for easier integration?

**Comment by RTL8710** [comment]
@hassanctech  @disa6302 @sirknightj   running error：
2024-05-22 18:43:10.263 ERROR   blockingCurlCall(): Curl perform failed for url https://cah7l82f9wtsm.credentials.iot.us-east-2.amazonaws.com/role-aliases/ipcamera_event_rule_alias/credentials with result SSL connect error : Failed - mbedTLS: ctr_drbg_init returned (-0x0034) CTR_DRBG - The entropy source failed
 
Failed with status 0x16000001

**Comment by hassanctech** [comment]
> @hassanctech  @disa6302 @sirknightj   running error：
> 
> 2024-05-22 18:43:10.263 ERROR   blockingCurlCall(): Curl perform failed for url https://cah7l82f9wtsm.credentials.iot.us-east-2.amazonaws.com/role-aliases/ipcamera_event_rule_alias/credentials with result SSL connect error : Failed - mbedTLS: ctr_drbg_init returned (-0x0034) CTR_DRBG - The entropy source failed
> 
>  
> 
> Failed with status 0x16000001

Can you please create a new issue since this appears to be unrelated to the original issue you encountered which is now resolved.
