### ISSUE TITLE
uclibc support and status?

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#52]
I found `ADD_MUCLIBC` option in CMakeLists.txt, but no more code relate to it.
Do we still support uclibc? AFAIK, some MIPS core camera devices need uclibc.

Thanks.

**Comment by chehefen** [comment]
yes we do support uclibc. The configuration is added in this pr: https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/55

**Comment by awsa2ron** [comment]
Thanks.
