### ISSUE TITLE
How to override callbacks easier?

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#8]
Looks I need to creat a callbacks structure and setup those callbacks and add them.
Could I just overwrite the the callback's function, which I need to modify, in user code? Like "weak" symbol does.

https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Function-Attributes.html

**Comment by MushMal** [comment]
@awsa2ron could you please describe in more details what you are trying to do and which asset you are attempting to use? If I am guessing correctly it's the C SDK? PIC (Platform Independent Codebase) has Producer Client object that's the root of the object graph which is created in 
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-pic/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1834

The callbacks object https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-pic/src/client/include/com/amazonaws/kinesis/video/client/Include.h#L1759 which is taken in as a parameter can be anything the higher layer specifies.

The C SDK is a layer that sits above and has a CallbackProvider object which provides polymorphism by having the first set of bits of the object be ClientCallback. The C SDK layer callbacks are split into the following groups:

* PlatformCallbacks
* ProducerCallbacks
* StreamCallbacks
* AuthCallbacks
* ApiCallbacks

which split the ClientCallbacks structure into logical sections/grouping.

The C SDK has a set of APIs that allow the customers code to create a default CallbackProvider object. For example: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L270

The customers that need extra behaviors can simply use one of the create APIs to create the callback provider object and then use a set of APIs to add sub-providers: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/include/com/amazonaws/kinesis/video/cproducer/Include.h#L378

The C SDK itself does this, for example: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/kinesis-video-c-producer/src/source/IotAuthCallback.c#L55

The callback providers will be called in sequence.


P.S. The C SDK is cross-platform/cross-compiler/cross-OS codebase and can't use compiler intrinsics.

**Comment by awsa2ron** [comment]
Thanks for the explanation, I will deep a little bit on those information.

**Comment by MushMal** [comment]
Resolving for now, please re-open if you have any further questions
