### ISSUE TITLE
Android publisher app not able to pass audio to viewer

### ISSUE THREAD

**Issue by swpnit82** [awslabs/amazon-kinesis-video-streams-producer-c#83]
Hi,
Urgently help required Android publisher app not able to pass audio to viewer.
Kinesis live is using 
gethlssessionurl is using for viewer.

Video is comming without any problem but audio is missing.

Thanks,
Swarup

**Comment by MushMal** [comment]
@swpnit82 it's not clear whether this is a C producer issue or Android issue.

If it's the latter, please open the issue in the Android SDK assets repository.

Try to include more information on what your scenario is, what you are attempting to do and what the expected results are.

Generally, the HLS session will ONLY work with multi-track where the audio is encoded in AAC or G711 (check the documentation). 

Make sure your producer produces multi-stream with proper content type

**Comment by swpnit82** [comment]
Hi MushMal,

It is android producer issue.
Please let me know the link of Android SDK assets repository

Thanks,
Swarup

**Comment by disa6302** [comment]
@swpnit82 , 

I think this is what you are looking for:
https://github.com/aws-amplify/aws-sdk-android
