### ISSUE TITLE
BUILD_STATIC=1 but libcurl still shared.

### ISSUE THREAD

**Issue by awsa2ron** [awslabs/amazon-kinesis-video-streams-producer-c#97]
Hi, 
I add  `set(BUILD_STATIC 1)` to CMakeList.txt, but I got this error when I run kvsAacAudioVideoStreamingSample without `open-source/lib/libcurl.so`

```
build$ ./kvsAacAudioVideoStreamingSample your-kvs-name 6000
./kvsAacAudioVideoStreamingSample: error while loading shared libraries: libcurl.so: cannot open shared object file: No such file or directory
```

**Comment by awsa2ron** [comment]
Hi,
I added 
```
if (BUILD_STATIC)
    set(CMAKE_ARGS ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=0 -DBUILD_TESTING=0)
endif()
```
to CMake/Dependencies/libcurl-CMakeLists.txt, but another error appeared:
```
[ 85%] Linking C shared library libcproducer.so
/usr/bin/ld: ../open-source/lib/libcurl.a(setopt.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/cproducer.dir/build.make:464: recipe for target 'libcproducer.so' failed
make[2]: *** [libcproducer.so] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/cproducer.dir/all' failed
make[1]: *** [CMakeFiles/cproducer.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by disa6302** [comment]
@awsa2ron , 

Looks like the appropriate build flag is not set for static libcurl generation. Can you try this PR and see if it solves your issue?
https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/98

I see you have added the flag, but maybe try cleaning the workspace and run cmake again?

**Comment by awsa2ron** [comment]
@disa6302 
Should I set the BUILD_STATIC to 1 in the header of CMakeLists.txt? Because I want to compile all of those libs static.

**Comment by disa6302** [comment]
@awsa2ron , 

Sure! If you want to compile all as static, you can add `set(BUILD_STATIC TRUE)` in CMakeLists.txt

**Comment by awsa2ron** [comment]
Thanks! @disa6302 

Could you kindly try to apply #98  to the latest version of kvs C producer and compile it?
I got same error:
```relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object;```

when `set(BUILD_STATIC TRUE)` in CMakeLists.txt line 25 and compile.

**Comment by awsa2ron** [comment]
BTW, I compile it in a docker:
`docker pull a2ron/mydocker:latest`

**Comment by awsa2ron** [comment]
@disa6302
Thank you for your help, I have build static on my Macbook with KVS+mbedTLS. But still failed in my docker.
Could you share with me your dockerfile or try my docker with `docker pull a2ron/mydocker:latest` on your side?

**Comment by disa6302** [comment]
@awsa2ron ,

I pulled `ubuntu18.04:latest` on docker and executed the commands in the README.md. Maybe you can try the dockerfile in https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-cpp/docker-amazonlinux and see if things work. Since it builds on Mac and Ubuntu (in my case), it looks more like a linking issue within your docker.

**Comment by awsa2ron** [comment]
I think I found a solution, change [CMakeLists.txt#L274](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/6d4f72f2b063ed65ca530b64ed88c002ad051546/CMakeLists.txt#L274) to STATIC will make it work.
